#' DII_PEPPER_INTAKE: Calculate the Pepper Component within the DII
#' @description
#' To calculate the pepper component within the Dietary Inflammatory Index (DII) for NHANES participants (NHANES 2001-2020), it is not recommended to use NHANES 1999-2000 due to the absence of an FNDDS file for that survey period. Recipes used to calculate pepper intake are detailed in the file titled 'Recipes used to calculate the intakes of garlic, ginger, onion, pepper, thyme, and oregano.xlsx', which can be downloaded from the following link: \url{https://github.com/zxucmu/dietaryindexNDP/blob/41f72620337c693037f7244ec5b88821d953df9e/Recipes%20used%20to%20calculate%20the%20intakes%20of%20garlic%20ginger%20onion%20pepper%20thyme%20and%20oregano.xlsx}.
#'
#' @param FLATTENED_FILEPATH A dataframe generated by the 'FNDDSSRLinks_FNDDSIngred_flattened' function to flatten a FNDDSSRLinks/FNDDSIngred file within a certain version of FNDDS.
#' @param DR1IFF_PATH The file path for the Individual Foods File for Day 1. The file names should be formatted like: DR1IFF_E.XPT, DRXIFF_B.XPT, etc. Alternatively, it can be a dataframe already imported into the Global Environment from files like DR1IFF_F.XPT, DRXIFF_B.XPT, etc.
#' @param DR2IFF_PATH The file path for the Individual Foods File for Day 2. The file names should be formatted like: DR2IFF_C.XPT, DRXIFF_B.XPT, etc. Alternatively, it can be a dataframe already imported into the Global Environment from files like DR2IFF_D.XPT, DRXIFF_B.XPT, etc.
#'
#' @return A dataframe with the variable name SEQN, and one or both of DR1TPEPPER and DR2TPEPPER. For DRXIFF_B, the variable name is DRXTPEPPER.
#' @export
#'
#' @examples
#' # Example 1
#' DII_PEPPER_INTAKE(FLATTENED_FILEPATH = fnddsSRlinks_4.1_flattened,
#'                   DR1IFF_PATH = './DR1IFF_E.XPT',
#'                   DR2IFF_PATH = './DR2IFF_E.XPT') # fnddsSRlinks_4.1_flattened is a dataframe generated by: fnddsSRlinks_4.1_flattened <- FNDDSSRLinks_FNDDSIngred_flattened(FNDDS = './FNDDS4.mdb').
#' # Example 2
#' DII_PEPPER_INTAKE(FLATTENED_FILEPATH = fnddsSRlinks_1314_flattened,
#'                   DR1IFF_PATH = dr1iff.h) # fnddsSRlinks_1314_flattened is a dataframe generated by: fnddsSRlinks_1314_flattened <- FNDDSSRLinks_FNDDSIngred_flattened(FNDDS = './FNDDS2013-2014.mdb'); dr1iff.h is a dataframe already imported into the Global Environment from file DR1IFF_H.XPT.
#' # Example 3
#' DII_PEPPER_INTAKE(FLATTENED_FILEPATH = fnddsIngred_1718_flattened,
#'                   DR2IFF_PATH = './DR2IFF_J.XPT') # fnddsIngred_1718_flattened is a dataframe generated by: fnddsIngred_1718_flattened <- FNDDSSRLinks_FNDDSIngred_flattened(FNDDS = './FNDDS_2017-2018.mdb').
#' # Example 4
#' DII_PEPPER_INTAKE(FLATTENED_FILEPATH = fnddsSRlinks_1.0_flattened,
#'                   DR1IFF_PATH = './DRXIFF_B.XPT',
#'                   DR2IFF_PATH = drxiff.b) # fnddsSRlinks_1.0_flattened is a dataframe generated by: fnddsSRlinks_1.0_flattened <- FNDDSSRLinks_FNDDSIngred_flattened(FNDDS = './FNDDS.mdb'); drxiff.b is a dataframe already imported into the Global Environment from file DRXIFF_B.XPT.
#' # Example 5
#' DII_PEPPER_INTAKE(FLATTENED_FILEPATH = fnddsSRlinks_1.0_flattened,
#'                   DR1IFF_PATH = './DRXIFF_B.XPT') # fnddsSRlinks_1.0_flattened is a dataframe generated by: fnddsSRlinks_1.0_flattened <- FNDDSSRLinks_FNDDSIngred_flattened(FNDDS = './FNDDS.mdb').
#' # Example 6
#' DII_PEPPER_INTAKE(FLATTENED_FILEPATH = fnddsSRlinks_1.0_flattened,
#'                   DR2IFF_PATH = './DRXIFF_B.XPT') # fnddsSRlinks_1.0_flattened is a dataframe generated by: fnddsSRlinks_1.0_flattened <- FNDDSSRLinks_FNDDSIngred_flattened(FNDDS = './FNDDS.mdb').
#' # Example 7
#' DII_PEPPER_INTAKE(FLATTENED_FILEPATH = fnddsSRlinks_1.0_flattened,
#'                   DR1IFF_PATH = drxiff,
#'                   DR2IFF_PATH = drxiff) # fnddsSRlinks_1.0_flattened is a dataframe generated by: fnddsSRlinks_1.0_flattened <- FNDDSSRLinks_FNDDSIngred_flattened(FNDDS = './FNDDS.mdb'); drxiff is a dataframe already imported into the Global Environment from file DRXIFF.XPT.
#' # Example 8
#' DII_PEPPER_INTAKE(FLATTENED_FILEPATH = fnddsSRlinks_1.0_flattened,
#'                   DR1IFF_PATH = './DRXIFF.XPT') # fnddsSRlinks_1.0_flattened is a dataframe generated by: fnddsSRlinks_1.0_flattened <- FNDDSSRLinks_FNDDSIngred_flattened(FNDDS = './FNDDS.mdb').
#' # Example 9
#' DII_PEPPER_INTAKE(FLATTENED_FILEPATH = fnddsSRlinks_1.0_flattened,
#'                   DR2IFF_PATH = './DRXIFF.XPT') # fnddsSRlinks_1.0_flattened is a dataframe generated by: fnddsSRlinks_1.0_flattened <- FNDDSSRLinks_FNDDSIngred_flattened(FNDDS = './FNDDS.mdb').
DII_PEPPER_INTAKE <- function(FLATTENED_FILEPATH = NULL, DR1IFF_PATH = NULL, DR2IFF_PATH = NULL){

  if (is.null(FLATTENED_FILEPATH)){
    if(is.null(DR1IFF_PATH) & is.null(DR2IFF_PATH)){
      stop("  Please provide the file path for the Flattened FNDDSSRLinks/FNDDSIngred file generated by the 'Flattening of FNDDSSRLinks or FNDDSIngred' function, along with Individual Foods Files for either Day 1, Day 2, or both.")
    }else{
      stop("  Please provide the file path for the Flattened FNDDSSRLinks/FNDDSIngred file generated by the 'Flattening of FNDDSSRLinks or FNDDSIngred' function.")
    }
  }else{
    if(is.null(DR1IFF_PATH) & is.null(DR2IFF_PATH)){
      stop("  Please provide Individual Foods Files for either Day 1, Day 2, or both.")
    }
  }

  FLATTENED_FILE <- FLATTENED_FILEPATH

  if('SR.code' %in% colnames(FLATTENED_FILE)){
    FLATTENED_FILE <- FLATTENED_FILE %>%
      dplyr::mutate(., 'NDB_No' = case_when(nchar(.$SR.code) == 4 ~ paste0('0', .$SR.code),
                                            nchar(.$SR.code) >= 5 ~ paste0(.$SR.code)))
  }
  if('Ingredient.code' %in% colnames(FLATTENED_FILE)){
    FLATTENED_FILE <- FLATTENED_FILE %>%
      dplyr::mutate(., 'NDB_No' = case_when(nchar(.$Ingredient.code) == 4 ~ paste0('0', .$Ingredient.code),
                                            nchar(.$Ingredient.code) >= 5 ~ paste0(.$Ingredient.code)))
  }

  message <- paste0(' The calculation of the pepper component within DII has been initiated. Please allow a moment for this process to complete')
  cat('\n')
  for (i in 1:3) {
    cat("\r", message, paste(rep(".", i), collapse = ""), "  ")
    Sys.sleep(1)
  }
  cat('\n')

  recipe_noCupEq <- c('11333', '02030', '11334', '11670', '11329', '02031', '11962', '11821', '11823', '11820', '11917', '11979', '11819', '11977', '11976', '11634', '31034')
  recipe_CupEq <- c('06962', '06961', '06452', '06169', '27052')
  # SR/Ingredient code 11333: Peppers, sweet, green, raw; Poblano pepper,raw; Sweet chili pepper
  # SR/Ingredient code 06962: Sauce, chili, peppers, hot, immature green, canned
  # SR/Ingredient code 02030: Spices, pepper, black
  # SR/Ingredient code 11334: Peppers, sweet, green, cooked, boiled, drained, without salt
  # SR/Ingredient code 11670: Peppers, hot chili, green, raw; Dwarf green pepper;need 1=4gms; DWARF GREEN PEPPER;need 1 oz raw yields x gms;2 oz AP needed; DWARF GREEN PEPPER, RAW
  # SR/Ingredient code 11329: Peppers, hot chili, green, canned, pods, excluding seeds, solids and liquids
  # SR/Ingredient code 02031: Spices, pepper, red or cayenne
  # SR/Ingredient code 11962: Peppers, hot chile, sun-dried
  # SR/Ingredient code 11821: Peppers, sweet, red, raw
  # SR/Ingredient code 06961: Sauce, peppers, hot, chili, mature red, canned
  # SR/Ingredient code 11823: Peppers, sweet, red, cooked, boiled, drained, without salt; PEPPR,SW,RD,DEHYDRATED
  # SR/Ingredient code 11820: Peppers, hot chili, red, canned, excluding seeds, solids and liquids
  # SR/Ingredient code 11917: Peppers, sweet, red, frozen, chopped, unprepared
  # SR/Ingredient code 11979: Peppers, jalapeno, raw
  # SR/Ingredient code 06452: Soup, pepperpot, canned, prepared with equal volume water, commercial
  # SR/Ingredient code 11819: Peppers, hot chili, red, raw
  # SR/Ingredient code 11977: Pepper, serrano, raw
  # SR/Ingredient code 11976: Pepper, banana, raw
  # SR/Ingredient code 06169: Sauce, ready-to-serve, pepper, TABASCO
  # SR/Ingredient code 11634: Peppers, sweet, green, freeze-dried
  # SR/Ingredient code 27052: Dip, cheese with chili peppers, ready-to-serve/Dip, salsa con queso, cheese and salsa-medium
  # SR/Ingredient code 31034: Peppers, hot pickled, canned

  # For more details about the SR/Ingredient codes used in calculating the pepper component for DII,
  #     please see the file titled 'The calculation for the garlic, ginger, onion, pepper, thyme, and oregano components in the DII' in the documentation folder.

  recipe_CupEq_Ref <- data.frame('SR_Ingredient_CODE' = c('6962', '6961', '6452', '6169', '27052'),
                                 'NDB_No' = recipe_CupEq,
                                 'Sum_V_OTHER_V_REDOR_OTHER (cup eq.)' = c(0.42, 0.4, 0.01, 0.25, 0.1),
                                 'Weight_perGram' = c(0.567, 0.54, 0.0135, 0.3375, 0.135))

  if (!is.null(FLATTENED_FILEPATH) & !is.null(DR1IFF_PATH)) {

    if (is.character(DR1IFF_PATH) == TRUE) {
      DR1IFF = haven::read_xpt(DR1IFF_PATH)
    }else {
      DR1IFF = DR1IFF_PATH
    }
    if (!(("DR1ILINE" %in% colnames(DR1IFF))|("DRXILINE" %in% colnames(DR1IFF)))) {
      stop("  Please utilize the Individual Foods File from the first day. The file names should adhere to the following format: DR1IFF_B.XPT, DR1IFF_C.XPT, DR1IFF_D.XPT, and so forth.")
    }

    cat('\n  Performing the calculation for the pepper component of DII based on the Individual Foods File from the first day.\n')

    if(("DR1ILINE" %in% colnames(DR1IFF))){
      dr1iff.pepper.SEQN <- setdiff(unique(DR1IFF$SEQN), unique(DR1IFF$SEQN[is.na(DR1IFF$DR1IGRMS)]))
      pb <- txtProgressBar(min = 0, max = length(dr1iff.pepper.SEQN), style = 3)

      dr1tot.pepper <- sapply(dr1iff.pepper.SEQN, simplify = F, function(x){

        setTxtProgressBar(pb, which(x == dr1iff.pepper.SEQN))

        DR1IFF.filter <- DR1IFF %>%
          dplyr::filter(., SEQN %in% x) %>%
          dplyr::select(., all_of(c('DR1IFDCD', 'DR1IGRMS')))
        recipe_intake <- sapply(c(1: nrow(DR1IFF.filter)), simplify = F, function(y){
          DR1IFDCD <- DR1IFF.filter$DR1IFDCD[y]
          DR1IGRMS <- DR1IFF.filter$DR1IGRMS[y]
          Weight_percent_noCupEq <- FLATTENED_FILE %>%
            dplyr::filter(., Food.code %in% DR1IFDCD) %>%
            dplyr::filter(., NDB_No %in% recipe_noCupEq) %>%
            dplyr::pull(., c('Weight_percent'))
          if(length(Weight_percent_noCupEq) == 0){
            recipe_intake_noCupEq <- 0
          }else{recipe_intake_noCupEq <- sum(Weight_percent_noCupEq * DR1IGRMS)}
          Weight_percent_CupEq <- FLATTENED_FILE %>%
            dplyr::filter(., Food.code %in% DR1IFDCD) %>%
            dplyr::right_join(., recipe_CupEq_Ref, by = 'NDB_No') %>%
            dplyr::mutate(., 'recipe_intake_CupEq' = .$Weight_percent * DR1IGRMS * .$Weight_perGram) %>%
            dplyr::pull(., 'recipe_intake_CupEq')
          if(length(Weight_percent_CupEq) == 0){
            recipe_intake_CupEq <- 0
          }else{recipe_intake_CupEq <- sum(Weight_percent_CupEq, na.rm = T)}
          recipe_intake <- recipe_intake_noCupEq + recipe_intake_CupEq

          recipe_individual <- data.frame('DR1IFDCD' = DR1IFDCD,
                                          'recipe_intake' = recipe_intake)
          return(recipe_individual)
        }) %>% bind_rows() %>%
          dplyr::pull(., all_of('recipe_intake')) %>% sum(.)
        recipe_individuals <- data.frame('SEQN' = x, 'Recipe' = recipe_intake)
        return(recipe_individuals)
      }) %>% bind_rows() %>%
        dplyr::rename(., 'DR1TPEPPER' = 'Recipe')
      cat('\n')
    }

    if(("DRXILINE" %in% colnames(DR1IFF))){
      dr1iff.pepper.SEQN <- setdiff(unique(DR1IFF$SEQN), unique(DR1IFF$SEQN[is.na(DR1IFF$DRXIGRMS)]))
      pb <- txtProgressBar(min = 0, max = length(dr1iff.pepper.SEQN), style = 3)
      dr1tot.pepper <- sapply(dr1iff.pepper.SEQN, simplify = F, function(x){
        setTxtProgressBar(pb, which(x == dr1iff.pepper.SEQN))
        DR1IFF.filter <- DR1IFF %>%
          dplyr::filter(., SEQN %in% x) %>%
          dplyr::select(., all_of(c('DRDIFDCD', 'DRXIGRMS')))
        recipe_intake <- sapply(c(1: nrow(DR1IFF.filter)), simplify = F, function(y){
          DR1IFDCD <- DR1IFF.filter$DRDIFDCD[y]
          DR1IGRMS <- DR1IFF.filter$DRXIGRMS[y]
          Weight_percent_noCupEq <- FLATTENED_FILE %>%
            dplyr::filter(., Food.code %in% DR1IFDCD) %>%
            dplyr::filter(., NDB_No %in% recipe_noCupEq) %>%
            dplyr::pull(., c('Weight_percent'))
          if(length(Weight_percent_noCupEq) == 0){
            recipe_intake_noCupEq <- 0
          }else{recipe_intake_noCupEq <- sum(Weight_percent_noCupEq * DR1IGRMS)}
          Weight_percent_CupEq <- FLATTENED_FILE %>%
            dplyr::filter(., Food.code %in% DR1IFDCD) %>%
            dplyr::right_join(., recipe_CupEq_Ref, by = 'NDB_No') %>%
            dplyr::mutate(., 'recipe_intake_CupEq' = .$Weight_percent * DR1IGRMS * .$Weight_perGram) %>%
            dplyr::pull(., 'recipe_intake_CupEq')
          if(length(Weight_percent_CupEq) == 0){
            recipe_intake_CupEq <- 0
          }else{recipe_intake_CupEq <- sum(Weight_percent_CupEq, na.rm = T)}
          recipe_intake <- recipe_intake_noCupEq + recipe_intake_CupEq

          recipe_individual <- data.frame('DR1IFDCD' = DR1IFDCD,
                                          'recipe_intake' = recipe_intake)
          return(recipe_individual)
        }) %>% bind_rows() %>%
          dplyr::pull(., all_of('recipe_intake')) %>% sum(.)
        recipe_individuals <- data.frame('SEQN' = x, 'Recipe' = recipe_intake)
        return(recipe_individuals)
      }) %>% bind_rows() %>%
        dplyr::rename(., 'DRXTPEPPER' = 'Recipe')
      cat('\n')

      if(!is.null(DR2IFF_PATH)){
        DR2IFF_PATH <- NULL
        cat('\n  Since there is only dietary intake data of one day included in NHANES 2001-2002, the pepper consumption is calculated based solely on the file pointed to by DR1IFF_PATH when both DR1IFF_PATH and DR2IFF_PATH lead to the same file.\n')
      }
    }
  }

  if (!is.null(FLATTENED_FILEPATH) & !is.null(DR2IFF_PATH)) {

    if (is.character(DR2IFF_PATH) == TRUE) {
      DR2IFF = haven::read_xpt(DR2IFF_PATH)
    }else {
      DR2IFF = DR2IFF_PATH
    }
    if (!(("DR2ILINE" %in% colnames(DR2IFF))|("DRXILINE" %in% colnames(DR2IFF)))) {
      stop("  Please use the Individual Foods File of the second day. The file name should be in the format like: DRXIFF_B.XPT, DR2IFF_C.XPT, DR2IFF_D.XPT, etc.")
    }

    cat('\n  Performing the calculation for the pepper component of DII based on the Individual Foods File from the second day.\n')

    if(("DR2ILINE" %in% colnames(DR2IFF))){
      dr2iff.pepper.SEQN <- setdiff(unique(DR2IFF$SEQN), unique(DR2IFF$SEQN[is.na(DR2IFF$DR2IGRMS)]))
      pb <- txtProgressBar(min = 0, max = length(dr2iff.pepper.SEQN), style = 3)
      dr2tot.pepper <- sapply(dr2iff.pepper.SEQN, simplify = F, function(x){
        setTxtProgressBar(pb, which(x == dr2iff.pepper.SEQN))
        DR2IFF.filter <- DR2IFF %>%
          dplyr::filter(., SEQN %in% x) %>%
          dplyr::select(., all_of(c('DR2IFDCD', 'DR2IGRMS')))
        recipe_intake <- sapply(c(1: nrow(DR2IFF.filter)), simplify = F, function(y){
          DR2IFDCD <- DR2IFF.filter$DR2IFDCD[y]
          DR2IGRMS <- DR2IFF.filter$DR2IGRMS[y]
          Weight_percent_noCupEq <- FLATTENED_FILE %>%
            dplyr::filter(., Food.code %in% DR2IFDCD) %>%
            dplyr::filter(., NDB_No %in% recipe_noCupEq) %>%
            dplyr::pull(., c('Weight_percent'))
          if(length(Weight_percent_noCupEq) == 0){
            recipe_intake_noCupEq <- 0
          }else{recipe_intake_noCupEq <- sum(Weight_percent_noCupEq * DR2IGRMS)}
          Weight_percent_CupEq <- FLATTENED_FILE %>%
            dplyr::filter(., Food.code %in% DR2IFDCD) %>%
            dplyr::right_join(., recipe_CupEq_Ref, by = 'NDB_No') %>%
            dplyr::mutate(., 'recipe_intake_CupEq' = .$Weight_percent * DR2IGRMS * .$Weight_perGram) %>%
            dplyr::pull(., 'recipe_intake_CupEq')
          if(length(Weight_percent_CupEq) == 0){
            recipe_intake_CupEq <- 0
          }else{recipe_intake_CupEq <- sum(Weight_percent_CupEq, na.rm = T)}
          recipe_intake <- recipe_intake_noCupEq + recipe_intake_CupEq

          recipe_individual <- data.frame('DR2IFDCD' = DR2IFDCD,
                                          'recipe_intake' = recipe_intake)
          return(recipe_individual)
        }) %>% bind_rows() %>%
          dplyr::pull(., all_of('recipe_intake')) %>% sum(.)
        recipe_individuals <- data.frame('SEQN' = x, 'Recipe' = recipe_intake)
        return(recipe_individuals)
      }) %>% bind_rows() %>%
        dplyr::rename(., 'DR2TPEPPER' = 'Recipe')
      cat('\n')
    }
    if(("DRXILINE" %in% colnames(DR2IFF))){
      dr2iff.pepper.SEQN <- setdiff(unique(DR2IFF$SEQN), unique(DR2IFF$SEQN[is.na(DR2IFF$DRXIGRMS)]))
      pb <- txtProgressBar(min = 0, max = length(dr2iff.pepper.SEQN), style = 3)
      dr2tot.pepper <- sapply(dr2iff.pepper.SEQN, simplify = F, function(x){
        setTxtProgressBar(pb, which(x == dr2iff.pepper.SEQN))
        DR2IFF.filter <- DR2IFF %>%
          dplyr::filter(., SEQN %in% x) %>%
          dplyr::select(., all_of(c('DRDIFDCD', 'DRXIGRMS')))
        recipe_intake <- sapply(c(1: nrow(DR2IFF.filter)), simplify = F, function(y){
          DR2IFDCD <- DR2IFF.filter$DRDIFDCD[y]
          DR2IGRMS <- DR2IFF.filter$DRXIGRMS[y]
          Weight_percent_noCupEq <- FLATTENED_FILE %>%
            dplyr::filter(., Food.code %in% DR2IFDCD) %>%
            dplyr::filter(., NDB_No %in% recipe_noCupEq) %>%
            dplyr::pull(., c('Weight_percent'))
          if(length(Weight_percent_noCupEq) == 0){
            recipe_intake_noCupEq <- 0
          }else{recipe_intake_noCupEq <- sum(Weight_percent_noCupEq * DR2IGRMS)}
          Weight_percent_CupEq <- FLATTENED_FILE %>%
            dplyr::filter(., Food.code %in% DR2IFDCD) %>%
            dplyr::right_join(., recipe_CupEq_Ref, by = 'NDB_No') %>%
            dplyr::mutate(., 'recipe_intake_CupEq' = .$Weight_percent * DR2IGRMS * .$Weight_perGram) %>%
            dplyr::pull(., 'recipe_intake_CupEq')
          if(length(Weight_percent_CupEq) == 0){
            recipe_intake_CupEq <- 0
          }else{recipe_intake_CupEq <- sum(Weight_percent_CupEq, na.rm = T)}
          recipe_intake <- recipe_intake_noCupEq + recipe_intake_CupEq

          recipe_individual <- data.frame('DR2IFDCD' = DR2IFDCD,
                                          'recipe_intake' = recipe_intake)
          return(recipe_individual)
        }) %>% bind_rows() %>%
          dplyr::pull(., all_of('recipe_intake')) %>% sum(.)
        recipe_individuals <- data.frame('SEQN' = x, 'Recipe' = recipe_intake)
        return(recipe_individuals)
      }) %>% bind_rows() %>%
        dplyr::rename(., 'DRXTPEPPER' = 'Recipe')
      cat('\n')
    }
  }

  cat('\n  The calculation for the pepper component of DII has been done.\n')

  if(!is.null(FLATTENED_FILEPATH) & !is.null(DR1IFF_PATH)){
    if(!is.null(FLATTENED_FILEPATH) & !is.null(DR2IFF_PATH)){
      dr12tot.pepper <- dplyr::full_join(dr1tot.pepper, dr2tot.pepper, by = 'SEQN')
      return(dr12tot.pepper)
    }else{
      return(dr1tot.pepper)
    }
  }else{
      return(dr2tot.pepper)
  }
  }
