#' DII_NHANES_CALCULATION: Incorporating Additional Components to Calculate the DII
#' @description
#' This function was developed based on the DII_NHANES_FPED() from the R package 'dietaryindex'. The calculation of the dietary inflammation index (DII) incorporates garlic, ginger, onion, pepper, and oregano/thyme in addition to the components used in the DII_NHANES_FPED() function for NHANES participants. Additionally, the intakes of flavan-3-ols, flavones, flavonols, flavonones, anthocyanidins, and isoflavones are included for participants from NHANES 2007-2010 and 2017-2018.
#'
#' @param FPED_PATH The file path for the total Food Patterns Equivalents Intakes per Individual for Day 1. The file name should be formatted like: fped_dr1tot_0708.sas7bdat, pyr_tot.sas7bdat, etc. Alternatively, it can be a dataframe already imported into the Global Environment from such files.
#' @param NUTRIENT_PATH The file path for the total Nutrient Intakes file for Day 1. The file name should be formatted like: DR1TOT_J.XPT, DRXTOT_B.XPT, etc. Alternatively, it can be a dataframe already imported into the Global Environment from files like DR1TOT_J.XPT, DRXTOT_B.XPT, etc.
#' @param DEMO_PATH The file path for the DEMOGRAPHIC data. The file name should be formatted like: DEMO_J.XPT. Alternatively, it can be a dataframe already imported into the Global Environment from files like DEMO_J.XPT.
#' @param FPED_PATH2 The file path for the total Food Patterns Equivalents Intakes per Individual for Day 2. The file name should be formatted like: fped_dr2tot_1718.sas7bdat, pyr_tot_d2.sas7bdat, etc. Alternatively, it can be a dataframe already imported into the Global Environment from files like fped_dr2tot_1718.sas7bdat, pyr_tot_d2.sas7bdat, etc.
#' @param NUTRIENT_PATH2 The file path for the total Nutrient Intakes file for Day 2. The file name should be formatted like: DR2TOT_D.XPT, DRXTOT_B.XPT, etc. Alternatively, it can be a dataframe already imported into the Global Environment from files like DR2TOT_D.XPT, DRXTOT_B.XPT, etc.
#' @param OTHER_INGREDIENTS A dataframe generated by the DII_ONESTEP_INTAKE() function that includes SEQN and the intakes of garlic, ginger, onion, pepper, oregano, thyme, flavan-3-ols, flavones, flavonols, flavonones, anthocyanidins, and isoflavones for Day 1, Day 2, or both.
#'
#' @return The DII and its component scores: DII is the total score (the sum of all components), while DII_NOETOH is the score without alcohol.
#' @export
#'
#' @examples
#' # Example 1
#' DII_NHANES_CALCULATION(FPED_PATH = fped_dr1tot_0910.sas7bdat,
#'                        NUTRIENT_PATH = DR1TOT_F.XPT,
#'                        DEMO_PATH = DEMO_F.XPT,
#'                        FPED_PATH2 = fped_dr2tot_0910.sas7bdat,
#'                        NUTRIENT_PATH2 = DR2TOT_F.XPT,
#'                        OTHER_INGREDIENTS = dii.nhanes.calculation.f) # dii.nhanes.calculation.f is a dataframe generated by the 'DII_ONE_INTAKE' function that includes SEQN and the intakes of garlic, ginger, onion, pepper, oregano, thyme, flavan-3-ols, flavones, flavonols, flavonones, anthocyanidins, and isoflavones for Day 1 and Day 2.
#' # Example 2
#' DII_NHANES_CALCULATION(FPED_PATH = fped_dr1tot_0708.sas7bdat,
#'                        NUTRIENT_PATH = dr1tot.e,
#'                        DEMO_PATH = DEMO_E.XPT,
#'                        OTHER_INGREDIENTS = dii.nhanes.calculation.e) # dr1tot.e is a dataframe already imported into the Global Environment from file DR1TOT_E.XPT; dii.nhanes.calculation.e is a dataframe generated by the 'DII_ONE_INTAKE' function that includes SEQN and the intakes of garlic, ginger, onion, pepper, oregano, thyme, flavan-3-ols, flavones, flavonols, flavonones, anthocyanidins, and isoflavones for Day 1 and Day 2.
#' # Example 3
#' DII_NHANES_CALCULATION(DEMO_PATH = DEMO_J.XPT,
#'                        FPED_PATH2 = fped_dr2tot_1718,
#'                        NUTRIENT_PATH2 = DR2TOT_J.XPT,
#'                        OTHER_INGREDIENTS = dii.nhanes.calculation.j) # fped_dr2tot_1718 is a dataframe already imported into the Global Environment from file fped_dr2tot_0708.sas7bdat; dii.nhanes.calculation.j is a dataframe generated by the 'DII_ONE_INTAKE' function that includes SEQN and the intakes of garlic, ginger, onion, pepper, oregano, thyme, flavan-3-ols, flavones, flavonols, flavonones, anthocyanidins, and isoflavones for Day 1 and Day 2.
#' # Example 4
#' DII_NHANES_CALCULATION(FPED_PATH = fped_dr1tot_0304.sas7bdat,
#'                        NUTRIENT_PATH = DR1TOT_C.XPT,
#'                        DEMO_PATH = demo.c) # demo.c is a dataframe already imported into the Global Environment from file DEMO_C.XPT.
#' # Example 5
#' DII_NHANES_CALCULATION(FPED_PATH = pyr_tot.sas7bdat,
#'                        NUTRIENT_PATH = DRXTOT_B.XPT,
#'                        DEMO_PATH = DEMO_B.XPT)
DII_NHANES_CALCULATION <- function (FPED_PATH = NULL, NUTRIENT_PATH = NULL, DEMO_PATH = NULL,
                             FPED_PATH2 = NULL, NUTRIENT_PATH2 = NULL, OTHER_INGREDIENTS = NULL) {
  if(!exists('FPED_PATH')){
    FPED_PATH <- NULL
  }
  if(!exists('NUTRIENT_PATH')){
    NUTRIENT_PATH <- NULL
  }
  if(!exists('DEMO_PATH')){
    DEMO_PATH <- NULL
  }
  if(!exists('FPED_PATH2')){
    FPED_PATH2 <- NULL
  }
  if(!exists('NUTRIENT_PATH2')){
    NUTRIENT_PATH2 <- NULL
  }
  if(!exists('OTHER_INGREDIENTS')){
    OTHER_INGREDIENTS <- NULL
  }

  if (is.null(FPED_PATH) & is.null(NUTRIENT_PATH) & is.null(FPED_PATH2) &
      is.null(NUTRIENT_PATH2)) {
    stop("  Please provide the file path for the FPED and Total Nutrient Intakes data for either Day 1, Day 2, or both.")
  }
  if (!is.null(FPED_PATH) & !is.null(NUTRIENT_PATH)) {
    if(!is.null(FPED_PATH2) & is.null(NUTRIENT_PATH2)){
      cat("\n  Caution: Since there is no Total Nutrient Intakes data for Day 2, the DII for that day cannot be calculated.")
    }
    if(is.null(FPED_PATH2) & !is.null(NUTRIENT_PATH2)){
      cat("\n  Caution: Since there is no FPED data for Day 2, the DII for that day cannot be calculated.")
    }
  }
  if (!is.null(FPED_PATH2) & !is.null(NUTRIENT_PATH2)) {
    if(!is.null(FPED_PATH) & is.null(NUTRIENT_PATH)){
      cat("\n  Caution: Since there is no Total Nutrient Intakes data for Day 1, the DII for that day cannot be calculated.")
    }
    if(is.null(FPED_PATH) & !is.null(NUTRIENT_PATH)){
      cat("\n  Caution: Since there is no FPED data for Day 1, the DII for that day cannot be calculated.")
    }
  }
  if (!is.null(OTHER_INGREDIENTS) & !(c('SEQN') %in% colnames(OTHER_INGREDIENTS))){
    stop("  Incorporating the respondent sequence number is essential when adding other components to the DII calculation, which the variable name should be 'SEQN'.")
  }

  # cat('\n  The calculation of the Dietary Inflammatory Index (DII) for NHANES participants has been initiated. Please hold on for a moment.\n')

  Variable = c("ALCOHOL", "VITB12", "VITB6", "BCAROTENE",
               "CAFFEINE", "CARB", "CHOLES", "KCAL", "EUGENOL", "TOTALFAT",
               "FIBER", "FOLICACID", "GARLIC", "GINGER", "IRON", "MG",
               "MUFA", "NIACIN", "N3FAT", "N6FAT", "ONION", "PROTEIN",
               "PUFA", "RIBOFLAVIN", "SAFFRON", "SATFAT", "SE", "THIAMIN",
               "TRANSFAT", "TURMERIC", "VITA", "VITC", "VITD", "VITE",
               "ZN", "TEA", "FLA3OL", "FLAVONES", "FLAVONOLS", "FLAVONONES",
               "ANTHOC", "ISOFLAVONES", "PEPPER", "THYME", "ROSEMARY")
  Overall_inflammatory_score = c(-0.278, 0.106, -0.365, -0.584,
                                 -0.11, 0.097, 0.11, 0.18, -0.14, 0.298, -0.663, -0.19,
                                 -0.412, -0.453, 0.032, -0.484, -0.009, -0.246, -0.436,
                                 -0.159, -0.301, 0.021, -0.337, -0.068, -0.14, 0.373,
                                 -0.191, -0.098, 0.229, -0.785, -0.401, -0.424, -0.446,
                                 -0.419, -0.313, -0.536, -0.415, -0.616, -0.467, -0.25,
                                 -0.131, -0.593, -0.131, -0.102, -0.013)
  Global_mean = c(13.98, 5.15, 1.47, 3718, 8.05, 272.2, 279.4,
                  2056, 0.01, 71.4, 18.8, 273, 4.35, 59, 13.35, 310.1,
                  27, 25.9, 1.06, 10.8, 35.9, 79.4, 13.88, 1.7, 0.37,
                  28.6, 67, 1.7, 3.15, 533.6, 983.9, 118.2, 6.26, 8.73,
                  9.84, 1.69, 95.8, 1.55, 17.7, 11.7, 18.05, 1.2, 10,
                  0.33, 1)
  SD = c(3.72, 2.7, 0.74, 1720, 6.67, 40, 51.2, 338, 0.08,
         19.4, 4.9, 70.7, 2.9, 63.2, 3.71, 139.4, 6.1, 11.77,
         1.06, 7.5, 18.4, 13.9, 3.76, 0.79, 1.78, 8, 25.1, 0.66,
         3.75, 754.3, 518.6, 43.46, 2.21, 1.49, 2.19, 1.53, 85.9,
         0.07, 6.79, 3.82, 21.14, 0.2, 7.07, 0.99, 15)
  DII_STD = data.frame(Variable, Overall_inflammatory_score,
                       Global_mean, SD)

  # This section was added later
  variable_dr1_spices <- c('DR1TGARLIC', 'DR1TGINGER', 'DR1TONION', 'DR1TPEPPER', 'DR1TTHYME', 'DR1TOREGANO')
  variable_dr2_spices <- c('DR2TGARLIC', 'DR2TGINGER', 'DR2TONION', 'DR2TPEPPER', 'DR2TTHYME', 'DR2TOREGANO')
  variable_drx_spices <- c('DRXTGARLIC', 'DRXTGINGER', 'DRXTONION', 'DRXTPEPPER', 'DRXTTHYME', 'DRXTOREGANO')
  spices_names <- c('garlic', 'ginger', 'onion', 'pepper', 'thyme', 'oregano')
  variable_dr1_flavonoids <- c("dr1t_fl_iso", "dr1t_fl_antho", "dr1t_fl_3_ols", "dr1t_fl_nones", "dr1t_fl_ones", "dr1t_fl_ols")
  variable_dr2_flavonoids <- c("dr2t_fl_iso", "dr2t_fl_antho", "dr2t_fl_3_ols", "dr2t_fl_nones", "dr2t_fl_ones", "dr2t_fl_ols")
  flavonoids_names <- c('isoflavones', 'anthocyanidins', 'flavan-3-ols', 'flavanones', 'flavones', 'flavonols')
  # End of added code block.

  # This function is to format a given vector of strings by adding commas between the elements and using "and" before the last element.
  add_commas_with_and <- function(vec){
    if (length(vec) == 0) return("")
    if (length(vec) == 1) return(vec)
    result <- paste(vec[-length(vec)], collapse = ", ")
    result <- paste(result, "and", vec[length(vec)], sep = " ")
    return(result)}

  # To calculate the DII of Day 1
  if (!is.null(FPED_PATH) & !is.null(NUTRIENT_PATH)) {
    if (is.character(FPED_PATH) == TRUE) {
      FPED = haven::read_sas(FPED_PATH)
    }else{
      FPED = FPED_PATH
    }
    if (is.character(NUTRIENT_PATH) == TRUE) {
      NUTRIENT = haven::read_xpt(NUTRIENT_PATH)
    }else{
      NUTRIENT = NUTRIENT_PATH
    }
    if (is.character(DEMO_PATH) == TRUE) {
      DEMO = haven::read_xpt(DEMO_PATH)
    }else{
      DEMO = DEMO_PATH
    }

    if ("DR1ILINE" %in% colnames(FPED) | "DR1ILINE" %in% colnames(NUTRIENT)) {
      stop("  Please use the population-level first day data. The file name should be like: Totals.csv")
    }
    if ("DRXILINE" %in% colnames(FPED) | "DRXILINE" %in% colnames(NUTRIENT)) {
      stop("  Please use the population-level first day data. The file name should be like: Totals.csv")
    }

    if("DR1TKCAL" %in% colnames(NUTRIENT)){
      cat('\n  The calculation of the DII for Day 1 has been initiated. Please hold on for a moment.\n')
    }
    if("DRXTKCAL" %in% colnames(NUTRIENT)){
      cat('\n  The calculation of the DII has been initiated. Please hold on for a moment.\n')
    }

    # This section was added later
    if(!is.null(OTHER_INGREDIENTS)){
      if("DR1TKCAL" %in% colnames(NUTRIENT)){
        INGREDIENTS <- OTHER_INGREDIENTS %>%
          subset.data.frame(., select = colnames(.) %in% c('SEQN', variable_dr1_spices, variable_dr2_spices, variable_dr1_flavonoids, variable_dr2_flavonoids))
      }
      if("DRXTKCAL" %in% colnames(NUTRIENT)){
        INGREDIENTS <- OTHER_INGREDIENTS %>%
          subset.data.frame(., select = colnames(.) %in% c('SEQN', variable_drx_spices))
      }
    }else{
      INGREDIENTS <- OTHER_INGREDIENTS
    }

    # The primary purpose of the code below is to check whether a data object (`OTHER_INGREDIENTS`) contains specific ingredients —
    #     namely garlic, ginger, onion, pepper, thyme, and oregano. Based on the results of this check, it outputs relevant warnings or cautionary messages
    #     to ensure that these ingredients are considered in the calculation of DII.
    if(!is.null(INGREDIENTS)){
      if("DR1TKCAL" %in% colnames(NUTRIENT)){
        dr1_spices_presence <- variable_dr1_spices %in% colnames(INGREDIENTS)

        if(sum(dr1_spices_presence) == 0){
          cat('\n  Warning: There are no components of garlic, ginger, onion, pepper, thyme and oregano included in the calculation of DII for Day 1. The relevant variable names should be DR1TGARLIC, DR1TGINGER, DR1ONION, DR1TPEPPER, DR1TTHYME and DR1TOREGANO, respectively. This absence may be attributed to the inclusion of these components from Day 2, the use of different variable names, or other factors.\n')
        }
        if(sum(dr1_spices_presence) > 0 & sum(dr1_spices_presence) < 6){
          spices_included <- spices_names[dr1_spices_presence]
          spices_notincluded <- spices_names[!dr1_spices_presence]
          if(length(spices_included) == 1){
            cat('\n')
            cat(paste0('  Caution: Since ', spices_included, ' is included in the calculation of DII for Day 1, it is recommended to also include ',
                       add_commas_with_and(spices_notincluded), ' in the calculation, with the variable name being ',
                       add_commas_with_and(variable_dr1_spices[!dr1_spices_presence]), ', repectively.', '\n'))
          }else{
            if(length(spices_notincluded) == 1){
              cat('\n')
              cat(paste0('  Caution: Since ', add_commas_with_and(spices_included), ' are included in the calculation of DII for Day 1, it is recommended to also include ',
                         add_commas_with_and(spices_notincluded), ' in the calculation, with the variable name being ',
                         add_commas_with_and(variable_dr1_spices[!dr1_spices_presence]), '.', '\n'))
            }else{
              cat('\n')
              cat(paste0('  Caution: Since ', add_commas_with_and(spices_included), ' are included in the calculation of DII for Day 1, it is recommended to also include ',
                         add_commas_with_and(spices_notincluded), ' in the calculation, with the variable name being ',
                         add_commas_with_and(variable_dr1_spices[!dr1_spices_presence]), ', repectively.', '\n'))
            }
          }
        }

      }
      if("DRXTKCAL" %in% colnames(NUTRIENT)){
        drx_spices_presence <- variable_drx_spices %in% colnames(INGREDIENTS)
        if(sum(drx_spices_presence) == 0){
          cat('\n  Warning: There are no components of garlic, ginger, onion, pepper, thyme and oregano included in the calculation of DII. The relevant variable names should be DRXTGARLIC, DRXTGINGER, DRXONION, DRXTPEPPER, DRXTTHYME and DRXTOREGANO, respectively. This absence may be attributed to the inclusion of these components from Day 2, the use of different variable names, or other factors.\n')
        }
        if(sum(drx_spices_presence) > 0 & sum(drx_spices_presence) < 6){
          spices_included <- spices_names[drx_spices_presence]
          spices_notincluded <- spices_names[!drx_spices_presence]
          if(length(spices_included) == 1){
            cat('\n')
            cat(paste0('  Caution: Since ', spices_included, ' is included in the calculation of DII, it is recommended to also include ',
                       add_commas_with_and(spices_notincluded), ' in the calculation, with the variable name being ',
                       add_commas_with_and(variable_drx_spices[!drx_spices_presence]), ', repectively.', '\n'))
          }else{
            if(length(spices_notincluded) == 1){
              cat('\n')
              cat(paste0('  Caution: Since ', add_commas_with_and(spices_included), ' are included in the calculation of DII, it is recommended to also include ',
                         add_commas_with_and(spices_notincluded), ' in the calculation, with the variable name being ',
                         add_commas_with_and(variable_drx_spices[!drx_spices_presence]), '.', '\n'))
            }else{
              cat('\n')
              cat(paste0('  Caution: Since ', add_commas_with_and(spices_included), ' are included in the calculation of DII, it is recommended to also include ',
                         add_commas_with_and(spices_notincluded), ' in the calculation, with the variable name being ',
                         add_commas_with_and(variable_drx_spices[!drx_spices_presence]), ', repectively.', '\n'))
            }
          }
        }
        if(sum(drx_spices_presence) == 6){
          cat('\n  Garlic, ginger, onion, pepper, thyme/oregano are included in the calculation of DII.\n')
        }
      }
    }

    if("DR1TKCAL" %in% colnames(NUTRIENT)){
      if(sum(dr1_spices_presence) == 6 & sum(variable_dr1_flavonoids %in% colnames(INGREDIENTS)) < 6){
        cat('\n  Garlic, ginger, onion, pepper, thyme/oregano are included in the calculation of DII for Day 1.\n')
      }
    }

    # The primary purpose of the code below is to check whether a data object (`OTHER_INGREDIENTS`) contains specific ingredients —
    #     namely isoflavones, anthocyanidins, flavan-3-ols, flavanones, flavones and flavonols. Based on the results of this check,
    #     it outputs relevant warnings or cautionary messages to ensure that these ingredients are considered in the calculation of DII.
    if(!is.null(INGREDIENTS)){
      if("DR1TKCAL" %in% colnames(NUTRIENT)){
        dr1_flavonoids_presence <- variable_dr1_flavonoids %in% colnames(INGREDIENTS)

        if(sum(dr1_flavonoids_presence) == 0){
          cat('\n  Warning: There are no components of isoflavones, anthocyanidins, flavan-3-ols, flavanones, flavones and flavonols included in the calculation of DII for Day 1. It is recommended that these flavonoids be included when calculating DII for participants of NHANES 2007-2008, 2009-2010 or 2017-2018. The relevant variable names should be dr1t_fl_iso, dr1t_fl_antho, dr1t_fl_3_ols, dr1t_fl_nones, dr1t_fl_ones, dr1t_fl_ols, respectively.\n')
        }
        if(sum(dr1_flavonoids_presence) > 0 & sum(dr1_flavonoids_presence) < 6){
          flavonoids_included <- flavonoids_names[dr1_flavonoids_presence]
          flavonoids_notincluded <- flavonoids_names[!dr1_flavonoids_presence]
          if(length(flavonoids_included) == 1){
            cat('\n')
            cat(paste0('  Caution: Since ', flavonoids_included, ' is included in the calculation of DII for Day 1, it is recommended to also include ',
                       add_commas_with_and(flavonoids_notincluded), ' in the calculation, with the variable name being ', add_commas_with_and(variable_dr1_flavonoids[!dr1_flavonoids_presence]), ', repectively.',
                       ' However, it is advisable for researchers to include these flavonoids only when calculating the DII for participants of NHANES 2007-2008, 2009-2010 or 2017-2018.\n'))
          }else{
            if(length(flavonoids_notincluded) == 1){
              cat('\n')
              cat(paste0('  Caution: Since ', add_commas_with_and(flavonoids_included), ' are included in the calculation of DII for Day 1, it is recommended to also include ',
                         add_commas_with_and(flavonoids_notincluded), ' in the calculation, with the variable name being ', add_commas_with_and(variable_dr1_flavonoids[!dr1_flavonoids_presence]), '.',
                         ' However, it is advisable for researchers to include these flavonoids only when calculating the DII for participants of NHANES 2007-2008, 2009-2010 or 2017-2018.\n'))
            }else{
              cat('\n')
              cat(paste0('  Caution: Since ', add_commas_with_and(flavonoids_included), ' are included in the calculation of DII for Day 1, it is recommended to also include ',
                         add_commas_with_and(flavonoids_notincluded), ' in the calculation, with the variable name being ', add_commas_with_and(variable_dr1_flavonoids[!dr1_flavonoids_presence]), ', repectively.',
                         ' However, it is advisable for researchers to include these flavonoids only when calculating the DII for participants of NHANES 2007-2008, 2009-2010 or 2017-2018.\n'))
            }
          }
        }
      }
    }
    if("DR1TKCAL" %in% colnames(NUTRIENT)){
      if(sum(dr1_spices_presence) == 6 & sum(dr1_flavonoids_presence) == 6){
        cat('\n  Garlic, ginger, onion, pepper, thyme/oregano, isoflavones, anthocyanidins, flavan-3-ols, flavanones, flavones and flavonols are included in the calculation of DII for Day 1. However, it is advisable for researchers to include these flavonoids only when calculating the DII for participants of NHANES 2007-2008, 2009-2010 or 2017-2018.\n')
      }

      if(sum(dr1_spices_presence) < 6 & sum(dr1_flavonoids_presence) == 6){
        cat('\n  Isoflavones, anthocyanidins, flavan-3-ols, flavanones, flavones and flavonols are included in the calculation of DII for Day 1. However, it is advisable for researchers to include these flavonoids only when calculating the DII for participants of NHANES 2007-2008, 2009-2010 or 2017-2018.\n')
      }
    }
    # End of added code block.


    if("DR1TKCAL" %in% colnames(NUTRIENT)){
      NUTRIENT = NUTRIENT %>% filter(DR1DRSTZ == 1) %>% arrange(SEQN)
      DEMO = DEMO %>% filter(RIDAGEYR >= 2) %>% dplyr::select(SEQN,
                                                              RIDAGEYR, RIAGENDR, SDDSRVYR, SDMVPSU, SDMVSTRA) %>%
        arrange(SEQN)
      FPED = FPED %>% arrange(SEQN)
      if(is.null(INGREDIENTS)){
        COHORT = NUTRIENT %>% inner_join(DEMO, by = c(SEQN = "SEQN")) %>%
          left_join(FPED, by = c(SEQN = "SEQN"))
      }else{
        COHORT = NUTRIENT %>% inner_join(DEMO, by = c(SEQN = "SEQN")) %>%
          left_join(FPED, by = c(SEQN = "SEQN")) %>%
          dplyr::left_join(., INGREDIENTS, by = c('SEQN')) # This line was added later
      }


      has_DR1TVD <- "DR1TVD" %in% colnames(COHORT)
      COHORT = COHORT %>% filter(DR1TKCAL > 0) %>% dplyr::mutate(ALCOHOL = DR1TALCO,
                                                                 VITB12 = DR1TVB12, VITB6 = DR1TVB6, BCAROTENE = DR1TBCAR,
                                                                 CAFFEINE = DR1TCAFF/1000, CARB = DR1TCARB, CHOLES = DR1TCHOL,
                                                                 KCAL = DR1TKCAL, TOTALFAT = DR1TTFAT, FIBER = DR1TFIBE,
                                                                 FOLICACID = DR1TFA, IRON = DR1TIRON, MG = DR1TMAGN,
                                                                 MUFA = DR1TMFAT, NIACIN = DR1TNIAC, N3FAT = DR1TP183 +
                                                                   DR1TP184 + DR1TP205 + DR1TP225 + DR1TP226, N6FAT = DR1TP182 +
                                                                   DR1TP204, PROTEIN = DR1TPROT, PUFA = DR1TPFAT,
                                                                 RIBOFLAVIN = DR1TVB2, SATFAT = DR1TSFAT, SE = DR1TSELE,
                                                                 THIAMIN = DR1TVB1, VITA = DR1TVARA, VITC = DR1TVC,
                                                                 VITD = if (has_DR1TVD)
                                                                   DR1TVD
                                                                 else NULL, VITE = DR1TATOC, ZN = DR1TZINC)


      # This section was added later
      spices_flavonoids_dr1_newnames <- c(toupper(spices_names), c("ISOFLAVONES", "ANTHOC", "FLA3OL", "FLAVONONES", "FLAVONES", "FLAVONOLS"))
      for (i in seq_along(c(variable_dr1_spices, variable_dr1_flavonoids))) {
        original_colname <- c(variable_dr1_spices, variable_dr1_flavonoids)[i]
        new_colname <- spices_flavonoids_dr1_newnames[i]
        COHORT[[new_colname]] <- COHORT[[original_colname]]
      }
      if(c('OREGANO' %in% colnames((COHORT)))){
        if(c('THYME' %in% colnames(COHORT))){
          COHORT <- COHORT %>%
            dplyr::mutate(., 'THYME' = .$THYME + .$OREGANO) %>%
            dplyr::select(., -all_of(c('OREGANO')))
        }else{
          COHORT <- COHORT %>%
            dplyr::mutate(., 'THYME' = .$OREGANO) %>%
            dplyr::select(., -all_of(c('OREGANO')))
        }
      }
      # End of added code block.


      select_cols <- c("SEQN", "ALCOHOL", "VITB12", "VITB6",
                       "BCAROTENE", "CAFFEINE", "CARB", "CHOLES", "KCAL",
                       "TOTALFAT", "FIBER", "FOLICACID", "IRON", "MG",
                       "MUFA", "NIACIN", "N3FAT", "N6FAT", "PROTEIN", "PUFA",
                       "RIBOFLAVIN", "SATFAT", "SE", "THIAMIN", "VITA",
                       "VITC", "VITE", "ZN", colnames(COHORT)[colnames(COHORT) %in% spices_flavonoids_dr1_newnames])
      if (has_DR1TVD) {
        select_cols <- c(select_cols, "VITD")
        cat("\n  VITD is included in the calculation of DII for the first day of NHANES dietary data.\n")
      }else {
        cat("\n  VITD is not included in the calculation of DII for the first day of NHANES dietary data.\n")
      }

      COHORT = COHORT %>% dplyr::select(one_of(select_cols)) %>%
        tidyr::pivot_longer(-SEQN, names_to = "Variable",
                            values_to = "Value")
      component_variable = setdiff(select_cols, "SEQN")
      COHORT = COHORT %>% dplyr::inner_join(DII_STD, by = c("Variable")) %>%
        dplyr::mutate(Z_SCORE = (Value - Global_mean)/SD,
                      PERCENTILE = pnorm(Z_SCORE) * 2 - 1, IND_DII_SCORE = PERCENTILE *
                        Overall_inflammatory_score) %>% tidyr::pivot_wider(names_from = Variable,
                                                                           values_from = IND_DII_SCORE) %>% dplyr::group_by(SEQN) %>%
        dplyr::summarize(DII_ALL = sum(across(all_of(component_variable),
                                              function(x) sum(x, na.rm = TRUE))), DII_NOETOH = sum(across(all_of(setdiff(component_variable,
                                                                                                                         "ALCOHOL")), function(x) sum(x, na.rm = TRUE))),
                         across(all_of(component_variable), function(x) sum(x,
                                                                            na.rm = TRUE)))
    }

    if("DRXTKCAL" %in% colnames(NUTRIENT)){
      NUTRIENT = NUTRIENT %>% filter(DRDDRSTZ == 1) %>% arrange(SEQN)
      DEMO = DEMO %>% filter(RIDAGEYR >= 2) %>% dplyr::select(SEQN,
                                                              RIDAGEYR, RIAGENDR, SDDSRVYR, SDMVPSU, SDMVSTRA) %>%
        arrange(SEQN)
      FPED = FPED %>% arrange(SEQN)
      if(is.null(INGREDIENTS)){
        COHORT = NUTRIENT %>% inner_join(DEMO, by = c(SEQN = "SEQN")) %>%
          left_join(FPED, by = c(SEQN = "SEQN"))
      }else{
        COHORT = NUTRIENT %>% inner_join(DEMO, by = c(SEQN = "SEQN")) %>%
          left_join(FPED, by = c(SEQN = "SEQN")) %>%
          dplyr::left_join(., INGREDIENTS, by = c('SEQN')) # This line was added later
      }


      has_DRXTVD <- "DRXTVD" %in% colnames(COHORT)
      COHORT = COHORT %>% filter(DRXTKCAL > 0) %>% dplyr::mutate(ALCOHOL = DRXTALCO,
                                                                 VITB12 = DRXTVB12, VITB6 = DRXTVB6, BCAROTENE = DRXTBCAR,
                                                                 CAFFEINE = DRXTCAFF/1000, CARB = DRXTCARB, CHOLES = DRXTCHOL,
                                                                 KCAL = DRXTKCAL, TOTALFAT = DRXTTFAT, FIBER = DRXTFIBE,
                                                                 FOLICACID = DRXTFA, IRON = DRXTIRON, MG = DRXTMAGN,
                                                                 MUFA = DRXTMFAT, NIACIN = DRXTNIAC, N3FAT = DRXTP183 +
                                                                   DRXTP184 + DRXTP205 + DRXTP225 + DRXTP226, N6FAT = DRXTP182 +
                                                                   DRXTP204, PROTEIN = DRXTPROT, PUFA = DRXTPFAT,
                                                                 RIBOFLAVIN = DRXTVB2, SATFAT = DRXTSFAT, SE = DRXTSELE,
                                                                 THIAMIN = DRXTVB1, VITA = DRXTVARA, VITC = DRXTVC,
                                                                 VITD = if (has_DRXTVD)
                                                                   DRXTVD
                                                                 else NULL, VITE = DRXTATOC, ZN = DRXTZINC)


      # This section was added later
      spices_drx_newnames <- c(toupper(spices_names))
      for (i in seq_along(c(variable_drx_spices))) {
        original_colname <- c(variable_drx_spices)[i]
        new_colname <- spices_drx_newnames[i]
        COHORT[[new_colname]] <- COHORT[[original_colname]]
      }
      if(c('OREGANO' %in% colnames((COHORT)))){
        if(c('THYME' %in% colnames(COHORT))){
          COHORT <- COHORT %>%
            dplyr::mutate(., 'THYME' = .$THYME + .$OREGANO) %>%
            dplyr::select(., -all_of(c('OREGANO')))
        }else{
          COHORT <- COHORT %>%
            dplyr::mutate(., 'THYME' = .$OREGANO) %>%
            dplyr::select(., -all_of(c('OREGANO')))
        }
      }
      # End of added code block.


      select_cols <- c("SEQN", "ALCOHOL", "VITB12", "VITB6",
                       "BCAROTENE", "CAFFEINE", "CARB", "CHOLES", "KCAL",
                       "TOTALFAT", "FIBER", "FOLICACID", "IRON", "MG",
                       "MUFA", "NIACIN", "N3FAT", "N6FAT", "PROTEIN", "PUFA",
                       "RIBOFLAVIN", "SATFAT", "SE", "THIAMIN", "VITA",
                       "VITC", "VITE", "ZN", colnames(COHORT)[colnames(COHORT) %in% spices_drx_newnames])
      if (has_DRXTVD) {
        select_cols <- c(select_cols, "VITD")
        cat("\n  VITD is included in the calculation of DII for the NHANES dietary data.\n")
      }else {
        cat("\n  VITD is not included in the calculation of DII.\n")
      }

      COHORT = COHORT %>% dplyr::select(one_of(select_cols)) %>%
        tidyr::pivot_longer(-SEQN, names_to = "Variable",
                            values_to = "Value")
      component_variable = setdiff(select_cols, "SEQN")
      COHORT = COHORT %>% dplyr::inner_join(DII_STD, by = c("Variable")) %>%
        dplyr::mutate(Z_SCORE = (Value - Global_mean)/SD,
                      PERCENTILE = pnorm(Z_SCORE) * 2 - 1, IND_DII_SCORE = PERCENTILE *
                        Overall_inflammatory_score) %>% tidyr::pivot_wider(names_from = Variable,
                                                                           values_from = IND_DII_SCORE) %>% dplyr::group_by(SEQN) %>%
        dplyr::summarize(DII_ALL = sum(across(all_of(component_variable),
                                              function(x) sum(x, na.rm = TRUE))), DII_NOETOH = sum(across(all_of(setdiff(component_variable,
                                                                                                                         "ALCOHOL")), function(x) sum(x, na.rm = TRUE))),
                         across(all_of(component_variable), function(x) sum(x,
                                                                            na.rm = TRUE)))
      if(!is.null(NUTRIENT_PATH2) | !is.null(FPED_PATH2)){
        NUTRIENT_PATH2 <- NULL
        FPED_PATH2 <- NULL
        cat('\n  Since there is only dietary intake data of one day included in NHANES 2001-2002, the DII is calculated based solely on the file pointed to by NUTRIENT_PATH when both NUTRIENT_PATH and NUTRIENT_PATH2 lead to the same file.\n')
      }
    }

    cat('\n  The DII calculation has been finished.\n')
  }

  # To calculate the DII of Day 2
  if (!is.null(FPED_PATH2) & !is.null(NUTRIENT_PATH2)) {
    if (is.character(FPED_PATH2) == TRUE) {
      FPED2 = haven::read_sas(FPED_PATH2)
    }
    else {
      FPED2 = FPED_PATH2
    }
    if (is.character(NUTRIENT_PATH2) == TRUE) {
      NUTRIENT2 = haven::read_xpt(NUTRIENT_PATH2)
    }
    else {
      NUTRIENT2 = NUTRIENT_PATH2
    }
    if (is.character(DEMO_PATH) == TRUE) {
      DEMO = haven::read_xpt(DEMO_PATH)
    }
    else {
      DEMO = DEMO_PATH
    }

    if ("DR2ILINE" %in% colnames(FPED2) | "DR2ILINE" %in%
        colnames(NUTRIENT2)) {
      stop("  Please use the population-level second day data. The file name should be like: Totals.csv")
    }
    if ("DRXILINE" %in% colnames(FPED2) | "DRXILINE" %in% colnames(NUTRIENT2)) {
      stop("  Please use the population-level first day data. The file name should be like: Totals.csv")
    }

    if("DR2TKCAL" %in% colnames(NUTRIENT2)){
      cat('\n  The calculation of the DII for Day 2 has been initiated. Please hold on for a moment.\n')
    }
    if("DRXTKCAL" %in% colnames(NUTRIENT2)){
      cat('\n  The calculation of the DII has been initiated. Please hold on for a moment.\n')
    }

    # This section was added later
    if(!is.null(OTHER_INGREDIENTS)){
      if("DR2TKCAL" %in% colnames(NUTRIENT2)){
        INGREDIENTS <- OTHER_INGREDIENTS %>%
          subset.data.frame(., select = colnames(.) %in% c('SEQN', variable_dr1_spices, variable_dr2_spices, variable_dr1_flavonoids, variable_dr2_flavonoids))
      }
      if("DRXTKCAL" %in% colnames(NUTRIENT2)){
        INGREDIENTS <- OTHER_INGREDIENTS %>%
          subset.data.frame(., select = colnames(.) %in% c('SEQN', variable_drx_spices))
      }
    }else{
      INGREDIENTS <- OTHER_INGREDIENTS
    }


    # The primary purpose of the code below is to check whether a data object (`OTHER_INGREDIENTS`) contains specific ingredients —
    #     namely garlic, ginger, onion, pepper, thyme, and oregano. Based on the results of this check, it outputs relevant warnings or cautionary messages
    #     to ensure that these ingredients are considered in the calculation of DII.
    if(!is.null(INGREDIENTS)){
      if("DR2TKCAL" %in% colnames(NUTRIENT2)){
      dr2_spices_presence <- variable_dr2_spices %in% colnames(INGREDIENTS)

      if(sum(dr2_spices_presence) == 0){
        cat('\n  Warning: There are no components of garlic, ginger, onion, pepper, thyme and oregano included in the calculation of DII for Day 2. The relevant variable names should be DR2TGARLIC, DR2TGINGER, DR2ONION, DR2TPEPPER, DR2TTHYME and DR2TOREGANO, respectively. This absence may be attributed to the inclusion of these components from Day 1, the use of different variable names, or other factors.\n')
      }
      if(sum(dr2_spices_presence) > 0 & sum(dr2_spices_presence) < 6){
        spices_included <- spices_names[dr2_spices_presence]
        spices_notincluded <- spices_names[!dr2_spices_presence]
        if(length(spices_included) == 1){
          cat(paste0('\n  Caution: Since ', spices_included, ' is included in the calculation of DII for Day 2, it is recommended to also include ',
                     add_commas_with_and(spices_notincluded), ' in the calculation, with the variable name being ',
                     add_commas_with_and(variable_dr2_spices[!dr2_spices_presence]), ', repectively.', '\n'))
        }else{
          if(length(spices_notincluded) == 1){
            cat(paste0('\n  Caution: Since ', add_commas_with_and(spices_included), ' are included in the calculation of DII for Day 2, it is recommended to also include ',
                       add_commas_with_and(spices_notincluded), ' in the calculation, with the variable name being ',
                       add_commas_with_and(variable_dr2_spices[!dr2_spices_presence]), '.', '\n'))
          }else{
            cat(paste0('\n  Caution: Since ', add_commas_with_and(spices_included), ' are included in the calculation of DII for Day 2, it is recommended to also include ',
                       add_commas_with_and(spices_notincluded), ' in the calculation, with the variable name being ',
                       add_commas_with_and(variable_dr2_spices[!dr2_spices_presence]), ', repectively.', '\n'))
          }
        }
      }
      }
      if("DRXTKCAL" %in% colnames(NUTRIENT2)){
        drx_spices_presence <- variable_drx_spices %in% colnames(INGREDIENTS)
        if(sum(drx_spices_presence) == 0){
          cat('\n  Warning: There are no components of garlic, ginger, onion, pepper, thyme and oregano included in the calculation of DII. The relevant variable names should be DRXTGARLIC, DRXTGINGER, DRXONION, DRXTPEPPER, DRXTTHYME and DRXTOREGANO, respectively. This absence may be attributed to the inclusion of these components from Day 2, the use of different variable names, or other factors.\n')
        }
        if(sum(drx_spices_presence) > 0 & sum(drx_spices_presence) < 6){
          spices_included <- spices_names[drx_spices_presence]
          spices_notincluded <- spices_names[!drx_spices_presence]
          if(length(spices_included) == 1){
            cat('\n')
            cat(paste0('  Caution: Since ', spices_included, ' is included in the calculation of DII, it is recommended to also include ',
                       add_commas_with_and(spices_notincluded), ' in the calculation, with the variable name being ',
                       add_commas_with_and(variable_drx_spices[!drx_spices_presence]), ', repectively.', '\n'))
          }else{
            if(length(spices_notincluded) == 1){
              cat('\n')
              cat(paste0('  Caution: Since ', add_commas_with_and(spices_included), ' are included in the calculation of DII, it is recommended to also include ',
                         add_commas_with_and(spices_notincluded), ' in the calculation, with the variable name being ',
                         add_commas_with_and(variable_drx_spices[!drx_spices_presence]), '.', '\n'))
            }else{
              cat('\n')
              cat(paste0('  Caution: Since ', add_commas_with_and(spices_included), ' are included in the calculation of DII, it is recommended to also include ',
                         add_commas_with_and(spices_notincluded), ' in the calculation, with the variable name being ',
                         add_commas_with_and(variable_drx_spices[!drx_spices_presence]), ', repectively.', '\n'))
            }
          }
        }
        if(sum(drx_spices_presence) == 6){
          cat('\n  Garlic, ginger, onion, pepper, thyme/oregano are included in the calculation of DII.\n')
        }
      }
    }

    if("DR2TKCAL" %in% colnames(NUTRIENT2)){
      if(sum(dr2_spices_presence) == 6 & sum(variable_dr2_flavonoids %in% colnames(INGREDIENTS)) < 6){
        cat('\n  Garlic, ginger, onion, pepper, thyme/oregano are included in the calculation of DII for Day 2.\n')
      }
    }

    # The primary purpose of the code below is to check whether a data object (`OTHER_INGREDIENTS`) contains specific ingredients —
    #     namely isoflavones, anthocyanidins, flavan-3-ols, flavanones, flavones and flavonols. Based on the results of this check,
    #     it outputs relevant warnings or cautionary messages to ensure that these ingredients are considered in the calculation of DII.
    if(!is.null(INGREDIENTS)){
      if("DR2TKCAL" %in% colnames(NUTRIENT2)){
        dr2_flavonoids_presence <- variable_dr2_flavonoids %in% colnames(INGREDIENTS)

        if(sum(dr2_flavonoids_presence) == 0){
          cat('\n  Warning: There are no components of isoflavones, anthocyanidins, flavan-3-ols, flavanones, flavones and flavonols included in the calculation of DII for Day 2. It is recommended that these flavonoids be included when calculating DII for participants of NHANES 2007-2008, 2009-2010 or 2017-2018. The relevant variable names should be dr2t_fl_iso, dr2t_fl_antho, dr2t_fl_3_ols, dr2t_fl_nones, dr2t_fl_ones, dr2t_fl_ols, respectively.\n')
        }
        if(sum(dr2_flavonoids_presence) > 0 & sum(dr2_flavonoids_presence) < 6){
          flavonoids_included <- flavonoids_names[dr2_flavonoids_presence]
          flavonoids_notincluded <- flavonoids_names[!dr2_flavonoids_presence]
          if(length(flavonoids_included) == 1){
            cat(paste0('\n  Caution: Since ', flavonoids_included, ' is included in the calculation of DII for Day 2, it is recommended to also include ',
                       add_commas_with_and(flavonoids_notincluded), ' in the calculation, with the variable name being ', add_commas_with_and(variable_dr2_flavonoids[!dr2_flavonoids_presence]), ', repectively.',
                       ' However, it is advisable for researchers to include these flavonoids only when calculating the DII for participants of NHANES 2007-2008, 2009-2010 or 2017-2018.\n'))
          }else{
            if(length(flavonoids_notincluded) == 1){
              cat(paste0('\n  Caution: Since ', add_commas_with_and(flavonoids_included), ' are included in the calculation of DII for Day 2, it is recommended to also include ',
                         add_commas_with_and(flavonoids_notincluded), ' in the calculation, with the variable name being ', add_commas_with_and(variable_dr2_flavonoids[!dr2_flavonoids_presence]), '.',
                         ' However, it is advisable for researchers to include these flavonoids only when calculating the DII for participants of NHANES 2007-2008, 2009-2010 or 2017-2018.\n'))
            }else{
              cat(paste0('\n  Caution: Since ', add_commas_with_and(flavonoids_included), ' are included in the calculation of DII for Day 2, it is recommended to also include ',
                         add_commas_with_and(flavonoids_notincluded), ' in the calculation, with the variable name being ', add_commas_with_and(variable_dr2_flavonoids[!dr2_flavonoids_presence]), ', repectively.',
                         ' However, it is advisable for researchers to include these flavonoids only when calculating the DII for participants of NHANES 2007-2008, 2009-2010 or 2017-2018.\n'))
            }
          }
        }
      }
    }
    if("DR2TKCAL" %in% colnames(NUTRIENT2)){
      if(sum(dr2_spices_presence) == 6 & sum(dr2_flavonoids_presence) == 6){
        cat('\n  Garlic, ginger, onion, pepper, thyme/oregano, isoflavones, anthocyanidins, flavan-3-ols, flavanones, flavones and flavonols are included in the calculation of DII for Day 2. It is advisable for researchers to include these flavonoids only when calculating the DII for participants of NHANES 2007-2008, 2009-2010 or 2017-2018.\n')
      }

      if(sum(dr2_spices_presence) < 6 & sum(dr2_flavonoids_presence) == 6){
        cat('\n  Isoflavones, anthocyanidins, flavan-3-ols, flavanones, flavones and flavonols are included in the calculation of DII for Day 2. However, it is advisable for researchers to include these flavonoids only when calculating the DII for participants of NHANES 2007-2008, 2009-2010 or 2017-2018.\n')
      }
    }
    # End of added code block.


    if("DR2TKCAL" %in% colnames(NUTRIENT2)){
      NUTRIENT2 = NUTRIENT2 %>% filter(DR2DRSTZ == 1) %>%
        arrange(SEQN)
      DEMO = DEMO %>% filter(RIDAGEYR >= 2) %>% dplyr::select(SEQN,
                                                              RIDAGEYR, RIAGENDR, SDDSRVYR, SDMVPSU, SDMVSTRA) %>%
        arrange(SEQN)
      FPED2 = FPED2 %>% arrange(SEQN)
      COHORT2 = NUTRIENT2 %>% inner_join(DEMO, by = c(SEQN = "SEQN")) %>%
        left_join(FPED2, by = c(SEQN = "SEQN")) %>%
        dplyr::left_join(., INGREDIENTS, by = c('SEQN')) # This line was added later

      has_DR2TVD <- "DR2TVD" %in% colnames(COHORT2)
      COHORT2 = COHORT2 %>% filter(DR2TKCAL > 0) %>% dplyr::mutate(ALCOHOL = DR2TALCO,
                                                                   VITB12 = DR2TVB12, VITB6 = DR2TVB6, BCAROTENE = DR2TBCAR,
                                                                   CAFFEINE = DR2TCAFF/1000, CARB = DR2TCARB, CHOLES = DR2TCHOL,
                                                                   KCAL = DR2TKCAL, TOTALFAT = DR2TTFAT, FIBER = DR2TFIBE,
                                                                   FOLICACID = DR2TFA, IRON = DR2TIRON, MG = DR2TMAGN,
                                                                   MUFA = DR2TMFAT, NIACIN = DR2TNIAC, N3FAT = DR2TP183 +
                                                                     DR2TP184 + DR2TP205 + DR2TP225 + DR2TP226, N6FAT = DR2TP182 +
                                                                     DR2TP204, PROTEIN = DR2TPROT, PUFA = DR2TPFAT,
                                                                   RIBOFLAVIN = DR2TVB2, SATFAT = DR2TSFAT, SE = DR2TSELE,
                                                                   THIAMIN = DR2TVB1, VITA = DR2TVARA, VITC = DR2TVC,
                                                                   VITD = if (has_DR2TVD)
                                                                     DR2TVD
                                                                   else NULL, VITE = DR2TATOC, ZN = DR2TZINC)


      # This section was added later
      spices_flavonoids_dr2_newnames <- c(toupper(spices_names), c("ISOFLAVONES", "ANTHOC", "FLA3OL", "FLAVONONES", "FLAVONES", "FLAVONOLS"))
      for (i in seq_along(c(variable_dr2_spices, variable_dr2_flavonoids))) {
        original_colname <- c(variable_dr2_spices, variable_dr2_flavonoids)[i]
        new_colname <- spices_flavonoids_dr2_newnames[i]
        COHORT2[[new_colname]] <- COHORT2[[original_colname]]
      }
      if(c('OREGANO' %in% colnames((COHORT2)))){
        if(c('THYME' %in% colnames(COHORT2))){
          COHORT2 <- COHORT2 %>%
            dplyr::mutate(., 'THYME' = .$THYME + .$OREGANO) %>%
            dplyr::select(., -all_of(c('OREGANO')))
        }else{
          COHORT2 <- COHORT2 %>%
            dplyr::mutate(., 'THYME' = .$OREGANO) %>%
            dplyr::select(., -all_of(c('OREGANO')))
        }
      }
      # End of added code block.

      select_cols <- c("SEQN", "ALCOHOL", "VITB12", "VITB6",
                       "BCAROTENE", "CAFFEINE", "CARB", "CHOLES", "KCAL",
                       "TOTALFAT", "FIBER", "FOLICACID", "IRON", "MG",
                       "MUFA", "NIACIN", "N3FAT", "N6FAT", "PROTEIN", "PUFA",
                       "RIBOFLAVIN", "SATFAT", "SE", "THIAMIN", "VITA",
                       "VITC", "VITE", "ZN", colnames(COHORT2)[colnames(COHORT2) %in% spices_flavonoids_dr2_newnames])
      if (has_DR2TVD) {
        select_cols <- c(select_cols, "VITD")
        cat("\n  VITD is included in the calculation of DII for the second day of NHANES dietary data.\n")
      }
      else {
        cat("\n  VITD is not included in the calculation of DII for the second day of NHANES dietary data.\n")
      }
      COHORT2 = COHORT2 %>% dplyr::select(one_of(select_cols)) %>%
        tidyr::pivot_longer(-SEQN, names_to = "Variable",
                            values_to = "Value")
      component_variable = setdiff(select_cols, "SEQN")
      COHORT2 = COHORT2 %>% dplyr::inner_join(DII_STD, by = c("Variable")) %>%
        dplyr::mutate(Z_SCORE = (Value - Global_mean)/SD,
                      PERCENTILE = pnorm(Z_SCORE) * 2 - 1, IND_DII_SCORE = PERCENTILE *
                        Overall_inflammatory_score) %>% tidyr::pivot_wider(names_from = Variable,
                                                                           values_from = IND_DII_SCORE) %>% dplyr::group_by(SEQN) %>%
        dplyr::summarize(DII_ALL = sum(across(all_of(component_variable),
                                              function(x) sum(x, na.rm = TRUE))), DII_NOETOH = sum(across(all_of(setdiff(component_variable,
                                                                                                                         "ALCOHOL")), function(x) sum(x, na.rm = TRUE))),
                         across(all_of(component_variable), function(x) sum(x,
                                                                            na.rm = TRUE)))
    }

    if(("DRXTKCAL" %in% colnames(NUTRIENT2))){
      NUTRIENT2 = NUTRIENT2 %>% filter(DRDDRSTZ == 1) %>% arrange(SEQN)
      DEMO = DEMO %>% filter(RIDAGEYR >= 2) %>% dplyr::select(SEQN,
                                                              RIDAGEYR, RIAGENDR, SDDSRVYR, SDMVPSU, SDMVSTRA) %>%
        arrange(SEQN)
      FPED2 = FPED2 %>% arrange(SEQN)
      if(is.null(INGREDIENTS)){
        COHORT2 = NUTRIENT2 %>% inner_join(DEMO, by = c(SEQN = "SEQN")) %>%
          left_join(FPED2, by = c(SEQN = "SEQN"))
      }else{
        COHORT2 = NUTRIENT2 %>% inner_join(DEMO, by = c(SEQN = "SEQN")) %>%
          left_join(FPED2, by = c(SEQN = "SEQN")) %>%
          dplyr::left_join(., INGREDIENTS, by = c('SEQN')) # This line was added later
      }


      has_DRXTVD <- "DRXTVD" %in% colnames(COHORT2)
      COHORT2 = COHORT2 %>% filter(DRXTKCAL > 0) %>% dplyr::mutate(ALCOHOL = DRXTALCO,
                                                                 VITB12 = DRXTVB12, VITB6 = DRXTVB6, BCAROTENE = DRXTBCAR,
                                                                 CAFFEINE = DRXTCAFF/1000, CARB = DRXTCARB, CHOLES = DRXTCHOL,
                                                                 KCAL = DRXTKCAL, TOTALFAT = DRXTTFAT, FIBER = DRXTFIBE,
                                                                 FOLICACID = DRXTFA, IRON = DRXTIRON, MG = DRXTMAGN,
                                                                 MUFA = DRXTMFAT, NIACIN = DRXTNIAC, N3FAT = DRXTP183 +
                                                                   DRXTP184 + DRXTP205 + DRXTP225 + DRXTP226, N6FAT = DRXTP182 +
                                                                   DRXTP204, PROTEIN = DRXTPROT, PUFA = DRXTPFAT,
                                                                 RIBOFLAVIN = DRXTVB2, SATFAT = DRXTSFAT, SE = DRXTSELE,
                                                                 THIAMIN = DRXTVB1, VITA = DRXTVARA, VITC = DRXTVC,
                                                                 VITD = if (has_DRXTVD)
                                                                   DRXTVD
                                                                 else NULL, VITE = DRXTATOC, ZN = DRXTZINC)


      # This section was added later
      spices_drx_newnames <- c(toupper(spices_names))
      for (i in seq_along(c(variable_drx_spices))) {
        original_colname <- c(variable_drx_spices)[i]
        new_colname <- spices_drx_newnames[i]
        COHORT[[new_colname]] <- COHORT[[original_colname]]
      }
      if(c('OREGANO' %in% colnames((COHORT2)))){
        if(c('THYME' %in% colnames(COHORT2))){
          COHORT2 <- COHORT2 %>%
            dplyr::mutate(., 'THYME' = .$THYME + .$OREGANO) %>%
            dplyr::select(., -all_of(c('OREGANO')))
        }else{
          COHORT2 <- COHORT2 %>%
            dplyr::mutate(., 'THYME' = .$OREGANO) %>%
            dplyr::select(., -all_of(c('OREGANO')))
        }
      }
      # End of added code block.


      select_cols <- c("SEQN", "ALCOHOL", "VITB12", "VITB6",
                       "BCAROTENE", "CAFFEINE", "CARB", "CHOLES", "KCAL",
                       "TOTALFAT", "FIBER", "FOLICACID", "IRON", "MG",
                       "MUFA", "NIACIN", "N3FAT", "N6FAT", "PROTEIN", "PUFA",
                       "RIBOFLAVIN", "SATFAT", "SE", "THIAMIN", "VITA",
                       "VITC", "VITE", "ZN", colnames(COHORT2)[colnames(COHORT2) %in% spices_drx_newnames])
      if (has_DRXTVD) {
        select_cols <- c(select_cols, "VITD")
        cat("\n  VITD is included in the calculation of DII for the NHANES dietary data.\n")
      }
      else {
        cat("\n  VITD is not included in the calculation of DII.\n")
      }

      COHORT2 = COHORT2 %>% dplyr::select(one_of(select_cols)) %>%
        tidyr::pivot_longer(-SEQN, names_to = "Variable",
                            values_to = "Value")
      component_variable = setdiff(select_cols, "SEQN")
      COHORT2 = COHORT2 %>% dplyr::inner_join(DII_STD, by = c("Variable")) %>%
        dplyr::mutate(Z_SCORE = (Value - Global_mean)/SD,
                      PERCENTILE = pnorm(Z_SCORE) * 2 - 1, IND_DII_SCORE = PERCENTILE *
                        Overall_inflammatory_score) %>% tidyr::pivot_wider(names_from = Variable,
                                                                           values_from = IND_DII_SCORE) %>% dplyr::group_by(SEQN) %>%
        dplyr::summarize(DII_ALL = sum(across(all_of(component_variable),
                                              function(x) sum(x, na.rm = TRUE))), DII_NOETOH = sum(across(all_of(setdiff(component_variable,
                                                                                                                         "ALCOHOL")), function(x) sum(x, na.rm = TRUE))),
                         across(all_of(component_variable), function(x) sum(x,
                                                                            na.rm = TRUE)))
    }
    cat('\n  The DII calculation has been finished.\n')
  }

  add_commas <- function(x){
    if(length(x) == 0){
      message <- c()
    }
    if(length(x) == 1){
      message <- paste0(x, ', ')
    }
    if(length(x) > 1){
      message <- paste0(paste(paste0(x, ','), collapse = " "), ' ')
    }
    return(message)
  }

  if (!is.null(FPED_PATH) & !is.null(NUTRIENT_PATH) & is.null(FPED_PATH2) & is.null(NUTRIENT_PATH2)) {
    if(exists('has_DR1TVD')){
      if(has_DR1TVD){
        dr1_spices_flavonoids_presence <- c(variable_dr1_spices, variable_dr1_flavonoids) %in% colnames(INGREDIENTS)
        if(sum(dr1_spices_flavonoids_presence) == 12){
          cat(paste0('\n  Reminder: Not all components within the original DII are considered in this calculation. For Day 1, the following are not included: Eugenol, trans fat, turmeric, Green/black tea and rosemary.\n'))
        }else{
          cat(paste0('\n  Reminder: Not all components within the original DII are considered in this calculation. For Day 1, the following are not included: Eugenol, ', add_commas(c(spices_names, flavonoids_names)[!dr1_spices_flavonoids_presence]),
                     'trans fat, turmeric, Green/black tea and rosemary.\n'))
        }
      }else{
        dr1_spices_flavonoids_presence <- c(variable_dr1_spices, variable_dr1_flavonoids) %in% colnames(INGREDIENTS)
        if(sum(dr1_spices_flavonoids_presence) == 12){
          cat(paste0('\n  Reminder: Not all components within the original DII are considered in this calculation. For Day 1, the following are not included: Vitamine D, eugenol, trans fat, turmeric, Green/black tea and rosemary.\n'))
        }else{
          cat(paste0('\n  Reminder: Not all components within the original DII are considered in this calculation. For Day 1, the following are not included: Vitamine D, eugenol, ', add_commas(c(spices_names, flavonoids_names)[!dr1_spices_flavonoids_presence]),
                     'trans fat, turmeric, Green/black tea and rosemary.\n'))
        }
      }
    }

    if(exists('has_DRXTVD')){
      if(has_DRXTVD){
        if(sum(drx_spices_presence) == 6){
          cat(paste0('\n  Reminder: Not all components within the original DII are considered in this calculation. The following are not included: Eugenol, trans fat, turmeric, Green/black tea and rosemary.\n'))
        }else{
          cat(paste0('\n  Reminder: Not all components within the original DII are considered in this calculation. The following are not included: Eugenol, ', add_commas(c(spices_names, flavonoids_names)[!drx_spices_presence]),
                     'trans fat, turmeric, Green/black tea and rosemary.\n'))
        }
      }else{
        if(sum(drx_spices_presence) == 6){
          cat(paste0('\n  Reminder: Not all components within the original DII are considered in this calculation. The following are not included: Vitamine D, eugenol, trans fat, turmeric, Green/black tea and rosemary.\n'))
        }else{
          cat(paste0('\n  Reminder: Not all components within the original DII are considered in this calculation. The following are not included: Vitamine D, eugenol, ', add_commas(c(spices_names, flavonoids_names)[!drx_spices_presence]),
                     'trans fat, turmeric, Green/black tea and rosemary.\n'))
        }
      }
    }

    return(COHORT)
  }

  if (is.null(FPED_PATH) & is.null(NUTRIENT_PATH) & !is.null(FPED_PATH2) & !is.null(NUTRIENT_PATH2)) {
    if(exists('has_DR2TVD')){
      if(has_DR2TVD){
        dr2_spices_flavonoids_presence <- c(variable_dr2_spices, variable_dr2_flavonoids) %in% colnames(INGREDIENTS)
        if(sum(dr2_spices_flavonoids_presence) == 12){
          cat(paste0('\n  Reminder: Not all components within the original DII are considered in this calculation. For Day 2, the following are not included: Eugenol, trans fat, turmeric, Green/black tea and rosemary.\n'))
        }else{
          cat(paste0('\n  Reminder: Not all components within the original DII are considered in this calculation. For Day 2, the following are not included: Eugenol, ', add_commas(c(spices_names, flavonoids_names)[!dr2_spices_flavonoids_presence]),
                     'trans fat, turmeric, Green/black tea and rosemary.\n'))
        }
      }else{
        dr2_spices_flavonoids_presence <- c(variable_dr2_spices, variable_dr2_flavonoids) %in% colnames(INGREDIENTS)
        if(sum(dr2_spices_flavonoids_presence) == 12){
          cat(paste0('\n  Reminder: Not all components within the original DII are considered in this calculation. For Day 2, the following are not included: Vitamine D, eugenol, trans fat, turmeric, Green/black tea and rosemary.\n'))
        }else{
          cat(paste0('\n  Reminder: Not all components within the original DII are considered in this calculation. For Day 2, the following are not included: Vitamine D, eugenol, ', add_commas(c(spices_names, flavonoids_names)[!dr2_spices_flavonoids_presence]),
                     'trans fat, turmeric, Green/black tea and rosemary.\n'))
        }
      }
    }
    if(exists('has_DRXTVD')){
      if(has_DRXTVD){
        if(sum(drX_spices_presence) == 6){
          cat(paste0('\n  Reminder: Not all components within the original DII are considered in this calculation. The following are not included: Eugenol, trans fat, turmeric, Green/black tea and rosemary.\n'))
        }else{
          cat(paste0('\n  Reminder: Not all components within the original DII are considered in this calculation. The following are not included: Eugenol, ', add_commas(c(spices_names, flavonoids_names)[!drx_spices_presence]),
                     'trans fat, turmeric, Green/black tea and rosemary.\n'))
        }
      }else{
        if(sum(drX_spices_presence) == 6){
          cat(paste0('\n  Reminder: Not all components within the original DII are considered in this calculation. The following are not included: Vitamine D, eugenol, trans fat, turmeric, Green/black tea and rosemary.\n'))
        }else{
          cat(paste0('\n  Reminder: Not all components within the original DII are considered in this calculation. The following are not included: Vitamine D, eugenol, ', add_commas(c(spices_names, flavonoids_names)[!drx_spices_presence]),
                     'trans fat, turmeric, Green/black tea and rosemary.\n'))
        }
      }
    }

    return(COHORT2)
  }

  if(!is.null(FPED_PATH) & !is.null(NUTRIENT_PATH) & !is.null(FPED_PATH2) &
     !is.null(NUTRIENT_PATH2)){
    common_cols <- intersect(colnames(COHORT), colnames(COHORT2))
    common_cols <- setdiff(common_cols, "SEQN")
    COHORT12 <- data.frame()
    if (length(common_cols) > 0) {
      COHORT12 <- inner_join(COHORT, COHORT2, by = "SEQN")
      avg_exprs <- setNames(lapply(common_cols, function(col) {
        rlang::parse_expr(paste0(col, " = (", col, ".x + ",
                                 col, ".y) / 2"))
      }), common_cols)
      COHORT12 <- COHORT12 %>% mutate(!!!avg_exprs)
      COHORT12 <- COHORT12 %>% dplyr::select(SEQN, !!!common_cols)

      dr1_spices_flavonoids_presence <- c(variable_dr1_spices, variable_dr1_flavonoids) %in% colnames(INGREDIENTS)
      dr2_spices_flavonoids_presence <- c(variable_dr2_spices, variable_dr2_flavonoids) %in% colnames(INGREDIENTS)

      if(has_DR1TVD & has_DR2TVD){
        cat(paste0('\n  Reminder: Not all components within the original DII are considered in this calculation. For Day 1, the following are not included: Eugenol, ', add_commas(c(spices_names, flavonoids_names)[!dr1_spices_flavonoids_presence]),
                   'trans fat, turmeric, Green/black tea and rosemary. For Day 2: Eugenol, ',
                   add_commas(c(spices_names, flavonoids_names)[!dr2_spices_flavonoids_presence]),
                   'trans fat, turmeric, Green/black tea and rosemary are not included.\n'))
      }
      if(has_DR1TVD & !has_DR2TVD){
        cat(paste0('\n  Reminder: Not all components within the original DII are considered in this calculation. For Day 1, the following are not included: Eugenol, ', add_commas(c(spices_names, flavonoids_names)[!dr1_spices_flavonoids_presence]),
                   ', trans fat, turmeric, Green/black tea and rosemary. For Day 2: Vitamin D, eugenol, ',
                   add_commas(c(spices_names, flavonoids_names)[!dr2_spices_flavonoids_presence]),
                   ', trans fat, turmeric, Green/black tea and rosemary are not included.\n'))
      }
      if(!has_DR1TVD & has_DR2TVD){
        cat(paste0('\n  Reminder: Not all components within the original DII are considered in this calculation. For Day 1, the following are not included: Vitamin D, eugenol, ', add_commas(c(spices_names, flavonoids_names)[!dr1_spices_flavonoids_presence]),
                   ', trans fat, turmeric, Green/black tea and rosemary. For Day 2: Eugenol, ',
                   add_commas(c(spices_names, flavonoids_names)[!dr2_spices_flavonoids_presence]),
                   ', trans fat, turmeric, Green/black tea and rosemary are not included.\n'))
      }
      if(!has_DR1TVD & !has_DR2TVD){
        cat(paste0('\n  Reminder: Not all components within the original DII are considered in this calculation. For Day 1, the following are not included: Vitamin D, eugenol, ', add_commas(c(spices_names, flavonoids_names)[!dr1_spices_flavonoids_presence]),
                   ', trans fat, turmeric, Green/black tea and rosemary. For Day 2: Vitamin D, eugenol, ',
                   add_commas(c(spices_names, flavonoids_names)[!dr2_spices_flavonoids_presence]),
                   ', trans fat, turmeric, Green/black tea and rosemary are not included.\n'))
      }

      return(COHORT12)
  }
  }
}

