#' DII_ONESTEP_INTAKE: Calculate Additional Components within the DII in One Step
#' @description
#' To calculate the garlic, ginger, onion, pepper, and thyme/oregano components within the Dietary Inflammatory Index(DII) for NHANES participants (NHANES 2001-2020), as well as flavan-3-ols, flavones, flavonols, flavonones, anthocyanidins, and isoflavones for NHANES 2007-2010 and 2017-2018. It is not recommended to calculate the intakes of garlic, ginger, onion, pepper, and thyme/oregano for NHANES 1999-2000 due to the absence of an FNDDS file for that survey period. Recipes used to calculate these intakes are detailed in the file titled 'Recipes used to calculate the intakes of garlic, ginger, onion, pepper, thyme, and oregano.xlsx', which can be downloaded from the following link: \url{https://github.com/zxucmu/dietaryindexNDP/blob/41f72620337c693037f7244ec5b88821d953df9e/Recipes%20used%20to%20calculate%20the%20intakes%20of%20garlic%20ginger%20onion%20pepper%20thyme%20and%20oregano.xlsx}.
#'
#' @param FLATTENED_FILEPATH A dataframe generated by the 'FNDDSSRLinks_FNDDSIngred_flattened' function to flatten a FNDDSSRLinks/FNDDSIngred file within a certain version of FNDDS.
#' @param DR1IFF_PATH The file path for the Individual Foods File for Day 1. The file names should be formatted like: DR1IFF_E.XPT, DRXIFF_B.XPT, etc. Alternatively, it can be a dataframe already imported into the Global Environment from files like DR1IFF_F.XPT, DRXIFF_B.XPT, etc.
#' @param DR2IFF_PATH The file path for the Individual Foods File for Day 2. The file names should be formatted like: DR2IFF_C.XPT, DRXIFF_B.XPT, etc. Alternatively, it can be a dataframe already imported into the Global Environment from files like DR2IFF_D.XPT, DRXIFF_B.XPT, etc.
#' @param FLAV_DR1TOT_PATH The file path for the Flavonoid Intake Data File for Day 1. The file names should be formatted like: flav_dr1tot_0710.sas7bdat, flav_dr1tot_1718.sas7bdat, etc. Alternatively, it can be a dataframe already imported into the Global Environment from files like flav_dr1tot_0710.sas7bdat, flav_dr1tot_1718.sas7bdat, etc.
#' @param FLAV_DR2TOT_PATH The file path for the Flavonoid Intake Data File for Day 2. The file names should be formatted like: flav_dr2tot_0708.sas7bdat, flav_dr2tot_1718.sas7bdat, etc. Alternatively, it can be a dataframe already imported into the Global Environment from files like flav_dr2tot_0708.sas7bdat, flav_dr2tot_1718.sas7bdat, etc.
#'
#' @return A dataframe with the variable name SEQN and variable names for the intakes of garlic, ginger, onion, pepper, thyme/oregano, isoflavones, anthocyanidins, flavan-3-ols, flavanones, flavones and flavonols for Day 1, Day 2, or both.
#' @export
#'
#' @examples
#' # Example 1
#' DII_ONESTEP_INTAKE(FLATTENED_FILEPATH = fnddsSRlinks_4.1_flattened,
#'                    DR1IFF_PATH = './DR1IFF_E.XPT',
#'                    DR2IFF_PATH = './DR2IFF_E.XPT',
#'                    FLAV_DR1TOT_PATH = './flav_dr1tot_0708.sas7bdat',
#'                    FLAV_DR2TOT_PATH = './flav_dr2tot_0708.sas7bdat') # fnddsSRlinks_4.1_flattened is a dataframe generated by: fnddsSRlinks_4.1_flattened <- FNDDSSRLinks_FNDDSIngred_flattened(FNDDS = './FNDDS4.mdb').
#' # Example 2
#' DII_ONESTEP_INTAKE(FLATTENED_FILEPATH = fnddsSRlinks_1314_flattened,
#'                    DR1IFF_PATH = './DR1IFF_H.XPT',
#'                    DR1IFF_PATH = './DR2IFF_H.XPT') # fnddsSRlinks_1314_flattened is a dataframe generated by: fnddsSRlinks_1314_flattened <- FNDDSSRLinks_FNDDSIngred_flattened(FNDDS = './FNDDS2013-2014.mdb').
#' # Example 3
#' DII_ONESTEP_INTAKE(FLATTENED_FILEPATH = fnddsSRlinks_1314_flattened,
#'                    DR1IFF_PATH = dr1iff.h) # fnddsSRlinks_1314_flattened is a dataframe generated by: fnddsSRlinks_1314_flattened <- FNDDSSRLinks_FNDDSIngred_flattened(FNDDS = './FNDDS2013-2014.mdb'); dr1iff.h is a dataframe already imported into the Global Environment from file DR1IFF_H.XPT.
#' # Example 4:
#' DII_ONESTEP_INTAKE(FLATTENED_FILEPATH = fnddsIngred_1516_flattened,
#'                    DR2IFF_PATH = './DR2IFF_I.XPT') # fnddsIngred_1516_flattened is a dataframe generated by: fnddsIngred_1516_flattened <- FNDDSSRLinks_FNDDSIngred_flattened(FNDDS = './FNDDS_2015-2016.mdb').
#' # Example 5
#' DII_ONESTEP_INTAKE(FLATTENED_FILEPATH = fnddsSRlinks_5.0_flattened,
#'                    DR1IFF_PATH = './DR1IFF_F.XPT',
#'                    FLAV_DR1TOT_PATH = flav_dr1tot_0710) # fnddsSRlinks_5.0_flattened is a dataframe generated by: fnddsSRlinks_5.0_flattened <- FNDDSSRLinks_FNDDSIngred_flattened(FNDDS = './FNDDS5.mdb'); flav_dr1tot_0710 is a dataframe already imported into the Global Environment from file flav_dr1tot_0708.sas7bdat.
#' # Example 6
#' DII_ONESTEP_INTAKE(FLATTENED_FILEPATH = fnddsSRlinks_5.0_flattened,
#'                    DR2IFF_PATH = dr2iff.f,
#'                    FLAV_DR2TOT_PATH = './flav_dr2tot_0710.sas7bdat') # fnddsSRlinks_5.0_flattened is a dataframe generated by: fnddsSRlinks_5.0_flattened <- FNDDSSRLinks_FNDDSIngred_flattened(FNDDS = './FNDDS5.mdb'); dr2iff.f is a dataframe already imported into the Global Environment from file DR2IFF_F.XPT.
#' # Example 7
#' DII_ONESTEP_INTAKE(FLATTENED_FILEPATH = fnddsSRlinks_1.0_flattened,
#'                    DR1IFF_PATH = './DRXIFF_B.XPT',
#'                    DR2IFF_PATH = drxiff.b) # fnddsSRlinks_1.0_flattened is a dataframe generated by: fnddsSRlinks_1.0_flattened <- FNDDSSRLinks_FNDDSIngred_flattened(FNDDS = './FNDDS.mdb'); drxiff.b is a dataframe already imported into the Global Environment from file DRXIFF_B.XPT.
#' # Example 8
#' DII_ONESTEP_INTAKE(FLATTENED_FILEPATH = fnddsSRlinks_1.0_flattened,
#'                    DR1IFF_PATH = drxiff.b) # fnddsSRlinks_1.0_flattened is a dataframe generated by: fnddsSRlinks_1.0_flattened <- FNDDSSRLinks_FNDDSIngred_flattened(FNDDS = './FNDDS.mdb'); drxiff.b is a dataframe already imported into the Global Environment from file DRXIFF_B.XPT.
#' # Example 9
#' DII_ONESTEP_INTAKE(FLATTENED_FILEPATH = fnddsSRlinks_1.0_flattened,
#'                    DR2IFF_PATH = './DRXIFF_B.XPT') # fnddsSRlinks_1.0_flattened is a dataframe generated by: fnddsSRlinks_1.0_flattened <- FNDDSSRLinks_FNDDSIngred_flattened(FNDDS = './FNDDS.mdb').
DII_ONESTEP_INTAKE <- function(FLATTENED_FILEPATH = NULL, DR1IFF_PATH = NULL, DR2IFF_PATH = NULL,
                               FLAV_DR1TOT_PATH = NULL, FLAV_DR2TOT_PATH = NULL){

  if(is.null(FLAV_DR1TOT_PATH) & is.null(FLAV_DR2TOT_PATH)){
    cat('\n  The calculation of garlic, ginger, onion, pepper, thyme, and oregano intakes for the DII has been initiated. To expedite the process, these intakes have been pre-calculated. Researchers can access this dietary data directly using the DII_ONESTEP_INTAKE_RESULT() function provided in this R package.\n')
  }else{
    cat('\n  The calculation of garlic, ginger, onion, pepper, thyme, oregano, isoflavones, anthocyanidins, flavan-3-ols, flavanones, flavones and flavonols intakes for the DII has been initiated. To expedite the process, these intakes have been pre-calculated. Researchers can access this dietary data directly using the DII_ONESTEP_INTAKE_RESULT() function provided in this R package.\n')
  }

  FLATTENED_FILE <- FLATTENED_FILEPATH
  DR1IFF <- DR1IFF_PATH
  DR2IFF <- DR2IFF_PATH
  FLAV_DR1TOT <- FLAV_DR1TOT_PATH
  FLAV_DR2TOT <- FLAV_DR2TOT_PATH

  GARLIC_INTAKE <- DII_GARLIC_INTAKE(FLATTENED_FILEPATH = FLATTENED_FILE, DR1IFF_PATH = DR1IFF, DR2IFF_PATH = DR2IFF)
  GINGER_INTAKE <- DII_GINGER_INTAKE(FLATTENED_FILEPATH = FLATTENED_FILE, DR1IFF_PATH = DR1IFF, DR2IFF_PATH = DR2IFF)
  ONION_INTAKE <- DII_ONION_INTAKE(FLATTENED_FILEPATH = FLATTENED_FILE, DR1IFF_PATH = DR1IFF, DR2IFF_PATH = DR2IFF)
  PEPPER_INTAKE <- DII_PEPPER_INTAKE(FLATTENED_FILEPATH = FLATTENED_FILE, DR1IFF_PATH = DR1IFF, DR2IFF_PATH = DR2IFF)
  THYME_INTAKE <- DII_THYME_INTAKE(FLATTENED_FILEPATH = FLATTENED_FILE, DR1IFF_PATH = DR1IFF, DR2IFF_PATH = DR2IFF)
  OREGANO_INTAKE <- DII_OREGANO_INTAKE(FLATTENED_FILEPATH = FLATTENED_FILE, DR1IFF_PATH = DR1IFF, DR2IFF_PATH = DR2IFF)
  if(is.null(FLAV_DR1TOT_PATH) & is.null(FLAV_DR2TOT_PATH)){
    FLAV_INTAKE <- NULL
  }else{
    # source(file = '.\\DII_FLAV_INTAKE.R')
    FLAV_INTAKE <- DII_FLAV_INTAKE(FLAV_DR1TOT_PATH = FLAV_DR1TOT, FLAV_DR2TOT_PATH = FLAV_DR2TOT)
  }

  if(is.null(FLAV_INTAKE)){
    DII_ONESTEP_INTAKE <- GARLIC_INTAKE %>%
      dplyr::full_join(., GINGER_INTAKE, by = 'SEQN') %>%
      dplyr::full_join(., ONION_INTAKE, by = 'SEQN') %>%
      dplyr::full_join(., PEPPER_INTAKE, by = 'SEQN') %>%
      dplyr::full_join(., THYME_INTAKE, by = 'SEQN') %>%
      dplyr::full_join(., OREGANO_INTAKE, by = 'SEQN')
  }else{
    DII_ONESTEP_INTAKE <- GARLIC_INTAKE %>%
      dplyr::full_join(., GINGER_INTAKE, by = 'SEQN') %>%
      dplyr::full_join(., ONION_INTAKE, by = 'SEQN') %>%
      dplyr::full_join(., PEPPER_INTAKE, by = 'SEQN') %>%
      dplyr::full_join(., THYME_INTAKE, by = 'SEQN') %>%
      dplyr::full_join(., OREGANO_INTAKE, by = 'SEQN') %>%
      dplyr::full_join(., FLAV_INTAKE, by = 'SEQN')
  }

  return(DII_ONESTEP_INTAKE)
}

