#' To flatten a FNDDSSRLinks or FNDDSIngred file within a specific version of the USDA Food and Nutrient Database for Dietary Studies (FNDDS)
#' @description
#' This function is to flatten a FNDDSSRLinks or FNDDSIngred file within a specific version of the FNDDS to ensure that all FNDDS food codes are ultimately linked to SR/Ingredient codes. The proportional weight contribution of all SR/Ingredient codes linked to each individual FNDDS food is also calculated.
#'
#' @param FNDDS_PATH The file path for a FNDDS file in Microsoft Access® format. The file names should be formatted like: FNDDS.mdb, FNDDS_2017-2018.mdb, etc. Alternatively, it can be a dataframe that has already been imported into the Global Environment from the table named FNDDSSRLinks or FNDDSIngred within an FNDDS file in Microsoft Access® format, such as FNDDS.mdb, FNDDS_2017-2018.mdb, etc. To obtain FNDDS files, please refer to the following link: http://www.ars.usda.gov/ba/bhnrc/fsrg.
#'
#' @return A dataframe generated by this function to flatten a FNDDSSRLinks/FNDDSIngred file within a certain version of FNDDS.
#' @export
#'
#' @examples
#' # Example 1
#' FNDDSSRLinks_FNDDSIngred_flattened(FNDDS_PATH = './FNDDS.mdb')
#' # Example 2
#' FNDDSSRLinks_FNDDSIngred_flattened(FNDDS_PATH = FNDDSSRLinks_2.0) # FNDDSSRLinks_2.0 is a dataframe that imported into the Global Environment from the table named FNDDSSRLinks within the FNDDS2.mdb file.
#' # Example 3
#' FNDDSSRLinks_FNDDSIngred_flattened(FNDDS_PATH = './FNDDS2013-2014.mdb')
#' # Example 4
#' FNDDSSRLinks_FNDDSIngred_flattened(FNDDS_PATH = FNDDSIngred_1718) # FNDDSIngred_1718 is a dataframe that has been imported into the Global Environment from the table named FNDDSIngred within FNDDS_2017-2018.mdb.
FNDDSSRLinks_FNDDSIngred_flattened <- function(FNDDS_PATH = NULL){

  if(is.null(FNDDS_PATH)){
    stop('  Please provide a version of the FNDDS specific to a particular NHANES survey period. The file names should adhere to the following format: FNDDS2.mdb, FNDDS2011-2012.mdb, FNDDS_2017-2018.mdb, and so forth.')
  }

  if(is.character(FNDDS_PATH) == TRUE) {
    conn <- DBI::dbConnect(odbc::odbc(), .connection_string = paste0("Driver={Microsoft Access Driver (*.mdb, *.accdb)};DBQ=", FNDDS_PATH))
    table_names <- DBI::dbListTables(conn)
    if('FNDDSSRLinks' %in% table_names){
      FNDDSSRLinks <- DBI::dbReadTable(conn, "FNDDSSRLinks")
    }
    if('FNDDSIngred' %in% table_names){
      FNDDSSRLinks <- DBI::dbReadTable(conn, "FNDDSIngred") %>%
        dplyr::mutate(.,
                      'SR.code' = 'Ingredient.code',
                      'SR.description' = 'Ingredient.description',
                      'Weight' = 'Ingredient.weight')
    }
  }else{
    FNDDSSRLinks = FNDDS_PATH
  }

  if(!(('Food.code' %in% colnames(FNDDSSRLinks) & 'SR.code' %in% colnames(FNDDSSRLinks) & 'SR.description' %in% colnames(FNDDSSRLinks) & 'Weight' %in% colnames(FNDDSSRLinks)) | ('Food.code' %in% colnames(FNDDSSRLinks) & 'Ingredient.code' %in% colnames(FNDDSSRLinks) & 'Ingredient.description' %in% colnames(FNDDSSRLinks) & 'Ingredient.weight' %in% colnames(FNDDSSRLinks)))){
    stop('  Either all of Food.code, SR.code, SR.description and Weight should be included, or all of Food.code, Ingredient.code, Ingredient.description and Ingredient.weight should be included in the FNDDSSRLinks or FNDDSIngred files within the FNDDS.\n')
  }

  message <- paste0(' The process of flattening the FNDDSSRLinks or FNDDSIngred file has been initiated. Please be patient while this process concludes')
  cat('\n')
  for (i in 1:3) {
    cat("\r", message, paste(rep(".", i), collapse = ""), "  ")
    Sys.sleep(1)
  }
  cat('\n')

  if(('Ingredient.code' %in% colnames(FNDDSSRLinks)) | ('Ingredient.description' %in% colnames(FNDDSSRLinks)) | ('Ingredient.weight' %in% colnames(FNDDSSRLinks))){
    FNDDSSRLinks <- FNDDSSRLinks  %>%
      dplyr::mutate(.,
                    'SR.code' = .$Ingredient.code,
                    'SR.description' = .$Ingredient.description,
                    'Weight' = .$Ingredient.weight)
  }

  cat("\n  The process of flattening the FNDDSSRLinks or FNDDSIngred file within the FNDDS is currently in progress. Please hold on for a moment.\n")

  Food.code <- unique(FNDDSSRLinks$Food.code)
  pb <- txtProgressBar(min = 0, max = length(Food.code), style = 3)
  FNDDSSRLinks_FNDDSIngred_flattened <- sapply(Food.code, simplify = F, function(X){
    setTxtProgressBar(pb, which(X == Food.code))

    FNDDSSRLinks_X <- FNDDSSRLinks %>% dplyr::filter(., Food.code == X)

    while(sum(FNDDSSRLinks_X$SR.code %in% Food.code) > 0){
      FNDDSSRLinks_Keep <- FNDDSSRLinks_X[!(FNDDSSRLinks_X$SR.code %in% Food.code), ]
      SR.code_Substitute <- FNDDSSRLinks_X$SR.code[FNDDSSRLinks_X$SR.code %in% Food.code]
      FNDDSSRLinks_Substitute <- sapply(unique(SR.code_Substitute), simplify = F, function(Y){
        Weight_Substitute <- FNDDSSRLinks_X$Weight[FNDDSSRLinks_X$SR.code == Y]
        if(length(Weight_Substitute) > 1){
          FNDDSSRLinks_Substitute <- sapply(c(1:length(Weight_Substitute)), simplify = F, function(Z){
            Weight_Substitute_count <- FNDDSSRLinks_X$Weight[(FNDDSSRLinks_X$SR.code == Y)][Z]
            FNDDSSRLinks_Substitute <- FNDDSSRLinks %>%
              dplyr::filter(., .$`Food.code` %in% Y) %>%
              dplyr::mutate(.,
                            'Amount' = Amount/sum(.$Amount)*Weight_Substitute_count,
                            'Weight' = Weight/sum(.$Weight)*Weight_Substitute_count,
                            'Food.code' = X)
              return(FNDDSSRLinks_Substitute)
            }) %>% bind_rows()}else{
              FNDDSSRLinks_Substitute <- FNDDSSRLinks %>%
                subset.data.frame(., Food.code %in% Y) %>%
                dplyr::mutate(.,
                              'Amount' = Amount/sum(.$Amount)*Weight_Substitute,
                              'Weight' = Weight/sum(.$Weight)*Weight_Substitute,
                              'Food.code' = X)
            }
      }) %>% bind_rows()

      FNDDSSRLinks_X <- bind_rows(FNDDSSRLinks_Keep, FNDDSSRLinks_Substitute)}

      FNDDSSRLinks_X <- FNDDSSRLinks_X %>%
        dplyr::mutate(., 'Weight_percent' = Weight/sum(Weight)) %>%
        dplyr::relocate(., 'Weight_percent', .after = 'Weight')
    }) %>% bind_rows()

  if(('Ingredient.code' %in% colnames(FNDDSSRLinks)) | ('Ingredient.description' %in% colnames(FNDDSSRLinks)) | ('Ingredient.weight' %in% colnames(FNDDSSRLinks))){
    cat('\n')
    cat("\n  The FNDDSIngred file within the FNDDS has been flattened.\n")
    FNDDSSRLinks_FNDDSIngred_flattened <- FNDDSSRLinks_FNDDSIngred_flattened  %>%
      dplyr::select(., -all_of(c('Ingredient.code', 'Ingredient.description', 'Ingredient.weight'))) %>%
      dplyr::rename(.,
                    'Ingredient.code' = 'SR.code',
                    'Ingredient.description' = 'SR.description',
                    'Ingredient.weight' = 'Weight')
    return(FNDDSSRLinks_FNDDSIngred_flattened)
  }

  if(('SR.code' %in% colnames(FNDDSSRLinks)) | ('SR.description' %in% colnames(FNDDSSRLinks)) | ('SR.weight' %in% colnames(FNDDSSRLinks))){
    cat('\n')
    cat("\n  The FNDDSSRLinks file within the FNDDS has been flattened.\n")
    return(FNDDSSRLinks_FNDDSIngred_flattened)
  }

  cat("\n  It is important to note that the 'SR.code' in the FNDDS 1.0, 2.0, 3.0, 4.1, 5.0, as well as the 2011-2012 and 2013-2014 FNDDSSRLinks files, has been reclassified as 'Ingredient.code' in the FNDDS 2015-2016, 2017-2018, and 2019-2020 FNDDSIngred files. Furthermore, 'SR.description' has been updated to 'Ingredient.description,' and 'Weight' has been modified to 'Ingredient.weight'.\n")
}
